### ISSUE TITLE
[convenience] Minimize tboard/wandb logspew 

### ISSUE THREAD

**Issue by moyapchen** [facebookresearch/metaseq#1]
We're currently logging a bunch of things at the layer level in tensorboard/wandb. While it's still good to have these logged somewhere (ex. in the `train.log`) they're clogging up the visualization. 

(making issue per discussion about a few other things with @stephenroller and @klshuster)

**Comment by suchenzang** [comment]
Already addressed in https://github.com/facebookresearch/metaseq/issues/277
