### ISSUE TITLE
How much GPU RAM is necessary to run the OPT-175B? and question about inferences/second

### ISSUE THREAD

**Issue by DeepTitan** [facebookresearch/metaseq#100]
1) A little confused on what is necessary here. In the documentation y'all mention 

**Where can I run this?**
_Right now only on Azure, as it requires the 80GB A100s. To enable it on other locations, we need to either try CPU offloading, or we need to use MP 16. FSDP should not be used because some workers will only be used for parameter hosting, and will not actually perform computations._

Does this mean that 80*8 = 320 GB of RAM would suffice for running the model? If that is the case, then it seems like there would be more options for hosting such as AWS g4dn.metal (384 GB RAM w/ 8 GPUs). Is this assumption correct?

2) Also quick question about how many inferences OPT-175B can make per second, y'all say 

**How fast is generation?**
_Slow. As of 2022-04-7, QPS is about 40 with 3 workers._

Does _QPS_ stand for Queries Per Second? Meaning that we are looking at about 25 ms per inference. The word Slow makes me think that I may also be misunderstanding something here. 

BTW Thanks so much for building this repo I love the work! Also thank you for the continued support!

**Comment by stephenroller** [comment]
The model is 350gb of weights. It won't naively fit on AWS which only gas 8x40gb nodes. It CAN work (should work already even) with 2 AWS nodes and careful setup. It's just very inefficient, as one node gets only used as spare RAM and not for computation. This can also be alleviated with some nontrivial logistical bookkeeping.

The model can fit on much smaller nodes via use if CPU or disk offloading. This will substantially increase latency, but generations will work. Think 1.5s/token generated vs 70ms/token which we're at now with the expensive hardware -- the generation becomes dominated by transferring weights back and forth.


That quoted Queries Per Second is a bit older. By the identical test I can get closer to 3x that these days.

However, QPS is a measure of throughput, not latency. We achieve high QPS by processing many generations in parallel, not sequentially. The average still can look good though.

Its also worth noting that 40QPS would immediately collapse under anything remotely resembling moderate load. 😀
