### ISSUE TITLE
How can I run it on my computer

### ISSUE THREAD

**Issue by simdok** [facebookresearch/metaseq#101]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by suchenzang** [comment]
What are you trying to run?

**Comment by simdok** [comment]
I'm trying to run the OPT

**Comment by suchenzang** [comment]
You will need access to V100 or A100 GPUs (# depends on which size you're running, and whether or not you're purely doing inference vs additional training / fine-tuning).  Please refer to our docs on getting started for help with him.

Models <= 30B in size are also available on HuggingFace: https://github.com/huggingface/transformers/releases/tag/v4.19.0 , which you can access via colab notebooks as well.

**Comment by simdok** [comment]
And how can I use the OPT-125M model on my computer through the code?

Em dom, 15 de mai de 2022 21:01, Susan Zhang ***@***.***>
escreveu:
