### ISSUE TITLE
OPT model for summarization

### ISSUE THREAD

**Issue by SagarBansal7** [facebookresearch/metaseq#119]
How can we utilize the model for specific downstream tasks such as Summarization or QA?

I have looked into the model versions released on HF that are primarily for text generation. I have tried to use those versions with the HF summarization pipeline but the results aren't great. I am planning to train the OPT-125m version for the summarization task with my data using Amazon Sagemaker (for distributed processing). 

I am wondering if there could be better alternatives. Any thoughts/comments? Thank you.

**Comment by suchenzang** [comment]
This won't be addressed via Github - we are focusing on code related issues here only, and not solving downstream tasks / open research problems.
