### ISSUE TITLE
shard_metadata not found

### ISSUE THREAD

**Issue by toanngosy** [facebookresearch/metaseq#125]
#### What is your question?
I run `python -m metaseq.scripts.consolidate_fsdp_shards ${FOLDER_PATH}/checkpoint_last --new-arch-name transformer_lm_gpt --save-prefix ${FOLDER_PATH}/consolidated` following #60 to merge the shards but I got this error: `metadata.append(ckpt["shard_metadata"])`

I tried on 125M and 1B3. How to fix the issues?

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0) 1.10.1+cu113
 - OS (e.g., Linux): Ubuntu 18.04 LTS
 - How you installed metaseq (`pip`, source): I followed the tutorials
 - Build command you used (if compiling from source):
 - Python version: 3.7.13
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: NVIDIA GeForce RTX 2060
 - Any other relevant information: N/A

**Comment by zhanghaoie** [comment]
have you soled this problem?
