### ISSUE TITLE
Error when build docker with Dockerfile

### ISSUE THREAD

**Issue by QIU-Shuo** [facebookresearch/metaseq#129]
## 🐛 Bug

1.  hydra-core 1.2 requires omegaconf~=2.2 and raise a conflict: error: omegaconf 2.1.1 is installed but omegaconf~=2.2 is required by {'hydra-core'}
3. Line 35 will raie an error: fatal: unable to access 'https://github.git/': Could not resolve host: github.git
4. I didn't encounter issue https://github.com/NVIDIA/nvidia-docker/issues/1631, and the workaround in line 8-9 raises an file not found error for me. They have probably fixed the docker, but I am not sure about this.

I have submit a PR for your reference: https://github.com/facebookresearch/metaseq/pull/130.

### To Reproduce
docker build -f Dockerfile .

### Expected behavior
Successfully built.

### Environment

 - metaseq Version (e.g., 1.0 or master): main
 - PyTorch Version (e.g., 1.0) As specified in dockerfile
 - OS (e.g., Linux, Windows, MacOS): As specified in dockerfile
 - How you installed metaseq (`pip`, source): As specified in dockerfile
 - Build command you used (if compiling from source): As specified in dockerfile
 - Python version: As specified in dockerfile
 - CUDA/cuDNN version: As specified in dockerfile
 - GPU models and configuration: A100
 - Any other relevant information:

**Comment by suchenzang** [comment]
@QIU-Shuo did your PR fix your issue mentioned here? We don't use docker in our workflows yet, so this isn't a feature we're testing right now.

**Comment by QIU-Shuo** [comment]
Thank you for your quick merge! Yes It can now built sucussfully. However I found several other problems while exploring metaseq inside docker, I will prepare another PR when I figure out how to solve them.
