### ISSUE TITLE
Add MyPy type checking to CI

### ISSUE THREAD

**Issue by m3rlin45** [facebookresearch/metaseq#14]
## 🚀 Feature Request
let's have typechecking, like in ParlAI: https://github.com/fairinternal/ParlAI-Internal/blob/705258b5799e69ef8942a8fc56928ad779e0980b/.github/workflows/lint.yml

### Motivation
It would be good to have some type checks (as suggestions, not a blocking test) to help catch common errors

### Pitch

probably can just copy/past from ParlAI:
https://github.com/fairinternal/ParlAI-Internal/blob/705258b5799e69ef8942a8fc56928ad779e0980b/.github/workflows/lint.yml

https://fb.workplace.com/100020258253907/posts/744791912872744/
Some slides about the ParlAI version

**Comment by TommyDew42** [comment]
Hi! It looks like a very good issue I can contribute. Is it possible I can pick this up?

**Comment by stephenroller** [comment]
Please Tommy, we would welcome!

**Comment by punitkoura** [comment]
Looks like this is done, closing
