### ISSUE TITLE
Question on hardware requirements for OPT-175B

### ISSUE THREAD

**Issue by shanestorks** [facebookresearch/metaseq#144]
Hello, and thank you for giving me access to OPT-175B! I'm working on setting it up on my institution's computing cluster. However, I noticed in the readme on the API functionality [here](https://github.com/facebookresearch/metaseq/blob/main/docs/api.md), it says that the model can only be run on Azure, as it requires 80GB A100 GPUs.

On our cluster, I have access to nodes that each have 8 48GB A40 GPUs. Based on my calculations of the model size, I was thinking this should be sufficient to run the model. But does this seem feasible? I would try it myself directly first, but it takes a long time to acquire all these resources in the shared environment!

Any ideas or advice are appreciated. Thanks for your time!

**Comment by zhisbug** [comment]
@shanestorks  H! Maybe give a try to [Alpa](https://github.com/alpa-projects/alpa)? 

We recently integrated OPT-175B serving with Alpa backend; it allows you to run big model training/inference on the cluster setup you described (lower-end GPUs than 80GB A100, but with sufficient total memory). 

See [this guide](https://alpa-projects.github.io/tutorials/opt_serving.html) on how to set up!

I'm [proposing a PR](https://github.com/facebookresearch/metaseq/issues/176) to put this integration in the Metaseq repo as well.

**Comment by stephenroller** [comment]
The MP16 work has landed (#214) for the faster 16x v100 support. Before that we did it with FSDP and MP8 but latency was AWFUL.

**Comment by stephenroller** [comment]
But total memory needs to exceed 350GB (so 8x48 is probably _barely_ enough). For that you can just use the MP8 checkpoints.

**Comment by shanestorks** [comment]
Thank you all for the suggestions! These new developments give us options to make OPT work with our hardware. Will close this issue for now as we will try these suggestions.
