### ISSUE TITLE
Generating OPT predictions on prompts

### ISSUE THREAD

**Issue by AnaRhisT94** [facebookresearch/metaseq#154]
Hi,

I'd like to know what's the process for setting up prompts (where can I find it in the code) for training to generate predictions on new ones?
I'm trying to use OPT-175B as an alternative to GPT-3.

Thanks a lot!

**Comment by suchenzang** [comment]
@AnaRhisT94 are you asking to generate from OPT-175B or to feed the model more data to train on / fine-tune with?

**Comment by AnaRhisT94** [comment]
> 

Hi,
I'm willing to finetune it on around 10k prompts.

**Comment by suchenzang** [comment]
This seems to be the same as https://github.com/facebookresearch/metaseq/issues/105 (adjusted to refer to finetuning).  We can follow-up there.
