### ISSUE TITLE
OPT 175B inference using accelerate

### ISSUE THREAD

**Issue by BalajiAJ** [facebookresearch/metaseq#162]
#### What is your question?

We have ran the OPT 30B model for inference, using the [accelerate](https://github.com/huggingface/accelerate) library, with multi GPU configuration. Reference notebook - [Accelerate_OPT](https://colab.research.google.com/drive/14wnxMvD9zsiBQo2FtTpxn6w2cpXCcb-7#scrollTo=XUlpcU3iQNhu&uniqifier=1).
So, can we use accelerate to run OPT 175B model, for inference, by loading consolidated shards?

#### What's your environment?

-metaseq Version (e.g., 1.0 or master):
-PyTorch Version (e.g., 1.0):
-OS (e.g., Linux): Linux
-How you installed metaseq (pip, source): source
-Build command you used (if compiling from source): Referred this link : [setup](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md)
-Python version: 3.7.12
-CUDA/cuDNN version: 11.2
-GPU models and configuration: 16 A100 40GB
-Any other relevant information:

**Comment by tbmihailov** [comment]
@stephenroller @patrickvonplaten Have you tried running the 175B model with HF?

**Comment by stephenroller** [comment]
I haven't.

**Comment by patrickvonplaten** [comment]
Haven't found the time yet either sadly

**Comment by zhisbug** [comment]
@BalajiAJ Just FYI -- if by any chance you haven't figured out how to serve the 175B model using the accelerate library, maybe try using [Alpa](https://github.com/alpa-projects/alpa) to serve it following [this guide ](https://alpa-projects.github.io/tutorials/opt_serving.html). 

With Alpa, you can actually serve that model using older generations of GPU  as long as your total memory suffices. You can try it out and let us know what you think about it!

**Comment by yeswanthkuruba** [comment]
[Accelerate_OPT](https://colab.research.google.com/drive/14wnxMvD9zsiBQo2FtTpxn6w2cpXCcb-7#scrollTo=XUlpcU3iQNhu&uniqifier=1). has lead to the below errors. Can you please help.

ValueError: /home/ubuntu/.cache/huggingface/hub/facebook--opt-30b.main.463007d7da4e87fe962909a027811a8c0b32ede8 containing mote than one `.index.json` file, delete the irrelevant ones.

**Comment by BalajiAJ** [comment]
> @BalajiAJ Just FYI -- if by any chance you haven't figured out how to serve the 175B model using the accelerate library, maybe try using [Alpa](https://github.com/alpa-projects/alpa) to serve it following [this guide ](https://alpa-projects.github.io/tutorials/opt_serving.html).
> 
> With Alpa, you can actually serve that model using older generations of GPU as long as your total memory suffices. You can try it out and let us know what you think about it!

@zhisbug Sure, we will try hosting using Alpa. Thank you!

**Comment by rekriz11** [comment]
> Hi @BalajiAJ ,
> 
> [Accelerate_OPT](https://colab.research.google.com/drive/14wnxMvD9zsiBQo2FtTpxn6w2cpXCcb-7#scrollTo=XUlpcU3iQNhu&uniqifier=1). has lead to the below errors.
> 
> load_checkpoint_and_dispatch( model.model, weights_path, device_map=device_map, offload_folder=offload_folder, dtype='float16', offload_state_dict=True ) model.tie_weights()
> 
> ValueError: /home/ubuntu/.cache/huggingface/hub/facebook--opt-30b.main.463007d7da4e87fe962909a027811a8c0b32ede8 containing mote than one `.index.json` file, delete the irrelevant ones.
> 
> Can you please help.

In case you haven't figured it out, for OPT-30B snapshot_download currently downloads 3 versions of the model (flax, tf, and pytorch). To run in Huggingface you just need the pytorch version, so you can move/delete the others, including the flax and tf index.json files.

**Comment by stephenroller** [comment]
@punitkoura has been working on this and just landed a PR with #214.
