### ISSUE TITLE
[Community] Add integration on serving OPT-175B using Alpa backend

### ISSUE THREAD

**Issue by zhisbug** [facebookresearch/metaseq#176]
### Motivation

Thanks for open sourcing the OPT model weights! 

With much help from [this thread](https://github.com/facebookresearch/metaseq/issues/122), we recently have integrated OPT serving with the [Alpa](https://github.com/alpa-projects/alpa) system (developed by UC Berkeley).

Alpa offers unique advantages to train or serve large OPT models with more flexible/heterogeneous cluster setup and GPU specs -- such as using many in-house clusters with lower-end GPUs (e.g., 40GB A100, V100, or even Titan X, 2080Ti), as long as the total memory is sufficient.

Alpa can also provide various types of parallelism strategies beyond FSDP and tensor model parallel, which might be more advantageous in certain cluster setups, e.g., multiple-node cluster, or cluster with limited communication bandwidth.

### Pitch

Like the [HuggingFace integration](https://github.com/facebookresearch/metaseq#using-opt-with--transformers) with OPT, We want to contribute a guide on how to setup OPT-175B serving (and later, inference or training if enough interest), so people who do not have 8x 80Gb A100 can still benefit from these weights by using Alpa.

We have generated a [setup guide](https://alpa-projects.github.io/tutorials/opt_serving.html) on our end. For the OPT-175B model, we have tested it on various cluster setups, such as 32x 16GB V100 (AWS p3.16x), or 12x 40GB V100, etc.

### Plan

I can draft a PR to Metaseq to describe how to use this integration and might need your review, what do you think? @stephenroller

**Comment by stephenroller** [comment]
Very cool

**Comment by gordicaleksa** [comment]
Hey guys - somewhat related, do you have any guide on how to run this on a single GPU?

Found [this comment](https://github.com/facebookresearch/metaseq/blob/main/metaseq/launcher/opt_baselines.py#L96) in [opt_baselines.py](https://github.com/facebookresearch/metaseq/blob/main/metaseq/launcher/opt_baselines.py) that led me to this PR.
