### ISSUE TITLE
Infrastructure recommanded for OPT-66B

### ISSUE THREAD

**Issue by emmanuelchauvin** [facebookresearch/metaseq#183]
What kind of infrastructure is recommanded to execute OPT-66B ? RAM, GPU, CPU, ...

**Comment by stephenroller** [comment]
The weights are 2*66GB so you need that much GPU VRAM. HuggingFace's accelerate may (should?) be able to handle it with less by offloading to CPU RAM.

**Comment by emmanuelchauvin** [comment]
thank you !

**Comment by emmanuelchauvin** [comment]
Just a remark : apparently HuggingFace's accelerate module is not working for inferences. Could we use Alpa instead of Accelerate ?
