### ISSUE TITLE
License restriction for OPT-66GB

### ISSUE THREAD

**Issue by emmanuelchauvin** [facebookresearch/metaseq#184]
Hello,

Do we have the same license restrictions for OPT-66GB than for OPT-175GB ?

Could we use OPT-66B for production purposes for ourself ?

Best regards.

**Comment by stephenroller** [comment]
All the OPT models are licensed as <a href="https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/MODEL_LICENSE.md">described here</a>.
