### ISSUE TITLE
How to measure the performance data of TFLOP/s?

### ISSUE THREAD

**Issue by weberxie** [facebookresearch/metaseq#185]
#### What is your question?
Thank you so much for the great work of your team! 

I'm going to reproduce the experiment, but I didn't find any tools of this project to measure this metric. So how did you collect the data `~147 TFLOP/s/GPU utilization on NVIDIA’s 80 GB A100 GPUs`?

#### What have you tried?
Searched the keyword "TFLOP" in this project.

Any response will be appreciated, thanks.

**Comment by stephenroller** [comment]
We have a spreadsheet that converts WPS to TFLOPs. The chinchilla paper has a very simple formula for estimating the flops of a forward-backward pass.

**Comment by weberxie** [comment]
Thank you @stephenroller , could you share the spreadsheet?

**Comment by suchenzang** [comment]
To be covered with https://github.com/facebookresearch/metaseq/issues/246 - closing as duplicate.
