### ISSUE TITLE
Missing dict.txt?

### ISSUE THREAD

**Issue by hunterlang** [facebookresearch/metaseq#19]
Hi, I've gotten to the point of running `metaseq-api-local` but I'm having issues figuring out where to find the missing stuff in `constants.py`.

I gathered I need `gpt2-merges.txt` and `gpt2-vocab.json`, so I downloaded those from [here](https://github.com/huggingface/swift-coreml-transformers/tree/master/Resources). But based on the example `ls` output in `constants.py`, I also need a `dict.txt`, and when I run `metaseq-api-local` I get 

```
File "/home/hlang/metaseq/metaseq/data/dictionary.py", line 235, in add_from_file
    with open(PathManager.get_local_path(f), "r", encoding="utf-8") as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/hlang/opt_models/dict.txt'
```

Here I have `MODEL_SHARED_FOLDER='/home/hlang/opt_models/'`.

Is there a place to download the `dict.txt` for each model?

**Comment by stephenroller** [comment]
To unblock this, here's the dict.txt file. Put it in the same folder as the .pt files.

https://gist.github.com/stephenroller/fbc74423445091531aa6b0452f5efaa2

**Comment by hunterlang** [comment]
Thanks, Stephen! That definitely gets me farther. Now I'm stuck on the next issue:
```
  File "/home/hlang/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
    self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
  File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
    return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
  File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
    assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
AssertionError: intra_layer_model parallel group is not initialized
```
Which seems like the same problem Patrick is running in to [here](https://github.com/patrickvonplaten/metaseq) (I'm also trying with the smallest model for now).

But closing this issue. Thanks for the help.

**Comment by stephenroller** [comment]
You need to specify --model-parallel N based on the settings of the particular model. (2 for 30B, 8 for 175B.)

**Comment by ParadoxZW** [comment]
About the problem `dict.txt`, I found that when point `LOCAL_SSD` to a different path with that of `MODEL_SHARED_FOLDER`, the program will automatically generate a  `dict.txt` in the folder of `LOCAL_SSD`. But this would not happen if `LOCAL_SSD = None` or `LOCAL_SSD = MODEL_SHARED_FOLDER`. Is this strange behavior a bug?

**Comment by xhlulu** [comment]
Here's what you can do to download all the files at once
```bash
export MODEL_SHARED_FOLDER="/path/to/your/opt/files"
cd $MODEL_SHARED_FOLDER
wget https://github.com/huggingface/swift-coreml-transformers/raw/master/Resources/gpt2-merges.txt
wget https://github.com/huggingface/swift-coreml-transformers/raw/master/Resources/gpt2-vocab.json
wget https://gist.githubusercontent.com/stephenroller/fbc74423445091531aa6b0452f5efaa2/raw/7e3353b2a8047d7ead5fee76876f5dd895045651/dict.txt
```

**Comment by guialfaro053** [comment]
> Thanks, Stephen! That definitely gets me farther. Now I'm stuck on the next issue:
> 
> ```
>   File "/home/hlang/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
>     self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
>   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
>     return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
>   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
>     assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
> AssertionError: intra_layer_model parallel group is not initialized
> ```
> 
> Which seems like the same problem Patrick is running in to [here](https://github.com/patrickvonplaten/metaseq) (I'm also trying with the smallest model for now).
> 
> But closing this issue. Thanks for the help.

HI Hunter, were you able to solve this problem? I have been getting the same error warning. If so, would you mind sharing how you solved it? Thanks

**Comment by stephenroller** [comment]
> > Thanks, Stephen! That definitely gets me farther. Now I'm stuck on the next issue:
> > ```
> >   File "/home/hlang/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
> >     self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
> >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
> >     return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
> >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
> >     assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
> > AssertionError: intra_layer_model parallel group is not initialized
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Which seems like the same problem Patrick is running in to [here](https://github.com/patrickvonplaten/metaseq) (I'm also trying with the smallest model for now).
> > But closing this issue. Thanks for the help.
> 
> HI Hunter, were you able to solve this problem? I have been getting the same error warning. If so, would you mind sharing how you solved it? Thanks

It should be that you need to set --model-parallel 8

**Comment by aarush7** [comment]
> > > Thanks, Stephen! That definitely gets me farther. Now I'm stuck on the next issue:
> > > ```
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
> > >     self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
> > >     return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
> > >     assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
> > > AssertionError: intra_layer_model parallel group is not initialized
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Which seems like the same problem Patrick is running in to [here](https://github.com/patrickvonplaten/metaseq) (I'm also trying with the smallest model for now).
> > > But closing this issue. Thanks for the help.
> > 
> > 
> > HI Hunter, were you able to solve this problem? I have been getting the same error warning. If so, would you mind sharing how you solved it? Thanks
> 
> It should be that you need to set --model-parallel 8

Where should we set this parameter?

**Comment by aarush7** [comment]
> > > Thanks, Stephen! That definitely gets me farther. Now I'm stuck on the next issue:
> > > ```
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/layers.py", line 190, in __init__
> > >     self.tensor_model_parallel_size = get_tensor_model_parallel_world_size()
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 258, in get_tensor_model_parallel_world_size
> > >     return torch.distributed.get_world_size(group=get_tensor_model_parallel_group())
> > >   File "/home/hlang/Megatron-LM/megatron/mpu/initialize.py", line 215, in get_tensor_model_parallel_group
> > >     assert _TENSOR_MODEL_PARALLEL_GROUP is not None, \
> > > AssertionError: intra_layer_model parallel group is not initialized
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Which seems like the same problem Patrick is running in to [here](https://github.com/patrickvonplaten/metaseq) (I'm also trying with the smallest model for now).
> > > But closing this issue. Thanks for the help.
> > 
> > 
> > HI Hunter, were you able to solve this problem? I have been getting the same error warning. If so, would you mind sharing how you solved it? Thanks
> 
> It should be that you need to set --model-parallel 8

Where should we set this parameter?

**Comment by Dev-hestabit** [comment]
@hunterlang, @aarush7 , @stephenroller , @guialfaro053, @ParadoxZW  hey, can you able to solve this issue?
i am trying to load 1.3B model but getting (AssertionError: intra_layer_model parallel group is not initialized) this error

**Comment by guialfaro053** [comment]
> @hunterlang, @aarush7 , @stephenroller , @guialfaro053, @ParadoxZW hey, can you able to solve this issue?
> i am trying to load 1.3B model but getting (AssertionError: intra_layer_model parallel group is not initialized) this error

I actually managed to run it after create a new conda env and installing everything again. 
I remember I had some conflicts with the Apex library and Fairseq

**Comment by Dev-hestabit** [comment]
i have tried creating conda env two times 
can you please suggest some steps that you follow to create your conda env if you remember.

**Comment by Dev-hestabit** [comment]
actually i am trying to run it on single GPU, if that is the issue then please suggest some solution.

**Comment by guialfaro053** [comment]
I installed all needed libraries from [here](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md). If there is an error while installing them, you won't be able to run BB3. It can take a while to install everything. 
Also, when I ran BB3 30B (it's a big model), I used two (A100 40Gb) GPUs so I really doubt you can run it with one single GPU without high specs.

**Comment by Dev-hestabit** [comment]
Actually i am trying to load 2.7B or 6.7B and i think it will work on A10G 24GB 
i have followed the same setup guide but it is not working for me

**Comment by xyjigsaw** [comment]
Any update? I encounter the same problem.
