### ISSUE TITLE
convert_to_singleton.py failed, missing glue_megatron_parts?

### ISSUE THREAD

**Issue by wgimperial** [facebookresearch/metaseq#192]
When run command " python -m metaseq.scripts.convert_to_singleton OPT-125M" 
ImportError: cannot import name 'glue_megatron_parts' from 'metaseq.distributed.stitch_fsdp_ckpt'

**Comment by suchenzang** [comment]
@stephenroller How did https://github.com/facebookresearch/metaseq/pull/60/files ever work with this missing method?

**Comment by stephenroller** [comment]
Looks like #169 refactored things and missed the issue. Might need @ngoyal2707 to weigh in if the change is just a drop in replace.

**Comment by punitkoura** [comment]
This was fixed in https://github.com/facebookresearch/metaseq/pull/206, with a small follow up fix coming up in https://github.com/facebookresearch/metaseq/pull/214

**Comment by punitkoura** [comment]
Closing this task for now, feel free to reopen if this issue persists after #214 is merged. Thanks
