### ISSUE TITLE
How to deploy OPT on AWS cluster?

### ISSUE THREAD

**Issue by johncs999** [facebookresearch/metaseq#196]
#### What is your question?

I can successfully run OPT in a single server after making several changes to `constant.py` script:
```
...
MODEL_SHARED_FOLDER = "/nvme/opt175b-8part/175B". # path to OPT

CHECKPOINT_FOLDER = MODEL_SHARED_FOLDER. # set to MODEL_SHARED_FOLDER
...
LAUNCH_ARGS = [
    ...
    #"--distributed-port 13000", #13000, comment out port
    ...
]

```

Now I want run OPT in AWS cluster:
 
- I've stored `/nvme/opt175b-8part/175B` to `s3:/NLP/opt/175B`.
- Then I run with `srun -p NLP --gres=gpu:8 -N1 --job-name=opt python3 -m metaseq_cli.interactive_hosted`. But it raise the following error:
```
...
Traceback (most recent call last):
  File "/mnt/cache/yejiacheng/.conda/envs/opt-py38/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/cache/yejiacheng/.conda/envs/opt-py38/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/mnt/cache/yejiacheng/metaseq/metaseq_cli/interactive_hosted.py", line 298, in <module>
    cli_main()
  File "/mnt/cache/yejiacheng/metaseq/metaseq_cli/interactive_hosted.py", line 279, in cli_main
    _copy_checkpoint_cache()
  File "/mnt/cache/yejiacheng/metaseq/metaseq_cli/interactive_hosted.py", line 272, in _copy_checkpoint_cache
    shutil.copytree(CHECKPOINT_FOLDER, os.path.dirname(CHECKPOINT_LOCAL))
  File "/mnt/cache/yejiacheng/.conda/envs/opt-py38/lib/python3.8/shutil.py", line 555, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 's3://NLP/opt/175B/'
```

I've tested that I have the access to NLP partition:
```
$ srun -p NLP --gres=gpu:8 -N1 --job-name=opt echo "hello"
phoenix-srun: job xxx queued and waiting for resources
phoenix-srun: job xxx has been allocated resources
phoenix-srun: Job xxx scheduled successfully!
Current QUOTA_TYPE is [reserved], which means the job has occupied quota in RESERVED_TOTAL under your partition.
Current PHX_PRIORITY is normal

hello
```
```
$ aws s3 ls s3://NLP/opt/175B
                           PRE 175B/
```

My question is how to set the path and deploy OPT on AWS cluster? 
Thanks for your help!

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.10.1+cu11.3
 - OS (e.g., Linux): Linux
 - How you installed metaseq (`pip`, source): pip
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.8.13
 - CUDA/cuDNN version: 11.3
 - GPU models and configuration: N/A
 - Any other relevant information: N/A

**Comment by suchenzang** [comment]
You will need to trace the code to see how it is trying to pull from s3 and save to local checkpoint directory.

**Comment by johncs999** [comment]
It seems metaseq didn't automatically download from s3. Do I need to download OPT to the calculating node first?

**Comment by stephenroller** [comment]
Yes, you'll need to build in some logic that copies from s3, or you'll want to copy it to a place accessible from workers.

**Comment by johncs999** [comment]
Problem solved, thanks!
