### ISSUE TITLE
How can I download the dataset?

### ISSUE THREAD

**Issue by rtaori** [facebookresearch/metaseq#20]
Hi, 
Is the preprocessed/filtered version of the dataset released somewhere? How can I download it?

**Comment by suchenzang** [comment]
Since the datasets are already publicly available, we aren't hosting and offering the dataset for download.

**Comment by rtaori** [comment]
I see, thanks for the quick reply.

Section 2.3 mentions some filtering & preprocessing scripts for each of the corpora. Are these scripts released? Where can I find them?

**Comment by stephenroller** [comment]
I'll post my post processing changes soon.

**Comment by rtaori** [comment]
Great, thanks so much! Looking forward!

**Comment by stephenroller** [comment]
> I'm particularly interested in how you concatenated messages of the Pushshift dataset (what delimiter did you use e.g.), as I'm trying to get a hand on fine-tuning OPT as a dialogue model.
> 
> It's not about how you flattened it, but more about the final format of data.

One message per line. I wish I had done better.

**Comment by stephenroller** [comment]
https://gist.github.com/stephenroller/8738a3e4fcbeae23dc5dbb87c8745d87 regex processing here

**Comment by ELFEamp** [comment]
Hello, thank you so much for your excellent work. I want to reproduce the training results. Would you mind providing the complete data preprocessing scripts?
