### ISSUE TITLE
 Dealing with Long Prompt (>2048 tokens)

### ISSUE THREAD

**Issue by johncs999** [facebookresearch/metaseq#200]
How best to prepare the prompt when the prompt is longer than the allowed 2049 after tokenized?

Roughly spliting the prompt by 'space' and keep ~1500 tokens could be a way, but I'm wondering if there is a better solution?

**Comment by stephenroller** [comment]
The model can't see context longer than 2048 tokens, and even then, it can only predict a single token. You should truncate the left side of the prompt until it fits and you have enough space for what you want to generate. You can extend your generation length by doing a sort of sliding window, but you can never fit more context.

**Comment by johncs999** [comment]
Thank you !
