### ISSUE TITLE
Some Questions in Training , need help

### ISSUE THREAD

**Issue by wgimperial** [facebookresearch/metaseq#201]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
We want to know the process of training and test how to train with our datas, we followed the doc in "Getting started with Training", and have some questions:
**Question 1:**
     What's the relationship betwwen opt-baselines command and metaseq-train command in doc of  "Getting started with Training" ?
     Should we execute all commands in doc to finish one training ? Or choose  one of opt-baselines command and metaseq-train command for one training? 
**Question 2:**
   What's the data like while using opt-baselines command with parameter --data , and what else shoud be placed in the data folder?
As we tried to download dataset described in the paper(OPT: Open Pre-trained Transformer Language Models), for example super_glue, and get some jsonl data files, what else should we do to process these jsonl data files?
**Question 3:** 
  What's the data like while using metaseq-train command, can show example of data-bin/pile-00 ?
**Question 4:**
  As we don't know how to use datas to train ,we test this:
`opt-baselines -n 1 -g 4 -p test_v0 --azure --model-size 125m --checkpoints-dir /home/datas/OPT-125M --local --benchmark`
(what does benchmark do ?)
and got some errors:
1) metaseq/benchmark/dummy_lm.py line 66, in load_dataset   RuntimeError: stack expects a non-empty TensorList.
and we modified bsz = max(1, self.cfg.batch_size) to avoid bsz = 0.
2) after above error, we got an new error:
RuntimeError: Mismatch between actual and expected iterable length. This may be caused by resuming training from a checkpoint using a different number of GPUs, in which case you can try the --reset-dataloader option. Alternatively you may have a train or validation set that is smaller than the number of GPUs. If none of these apply, please report this to the metaseq developers.
we tried add parameter --reset-dataloader like this:
`opt-baselines -n 1 -g 4 -p test_v0 --azure --model-size 125m --checkpoints-dir /home/datas/OPT-125M --local --benchmark --reset-dataloader` did not work, and we have no idea how to continue training.

#### What's your environment?
 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0):  1.10.1+cu113
 - OS (e.g., Linux):  Ubuntu 20.04
 - How you installed metaseq (`pip`, source):  source
 - Build command you used (if compiling from source): yes
 - Python version: 3.8
 - CUDA/cuDNN version: CUDA11.3/cuDNN 8.2.0
 - GPU models and configuration: one node with 4 * 16G Tesla4 GPU
 - Any other relevant information:

**Comment by stephenroller** [comment]
Marking this as done. Reopen if you need to.
