### ISSUE TITLE
fairinternal/metaseq.git required by setup.md is not available

### ISSUE THREAD

**Issue by codeisnotcode** [facebookresearch/metaseq#21]
## 🐛 Bug

setup.md instructs that metaseq should be installed using: 
git clone https://github.com/fairinternal/metaseq.git

However, as of 5/3/2022 at 11:40 AM PDT, fairinternal has no publicly accessible repository metaseq

### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run command: git clone https://github.com/fairinternal/metaseq.git
2. Response is: Username for 'https://github.com':
3. In my experience, this response can occur because the respository does not exist, or because it exists but is not publicly accessible.  
4. To further investigate, go to web page https://github.com/orgs/fairinternal/repositories and note that no repository metaseq appears.

#### Code sample

See above

### Expected behavior

I expected step 1. above to create a clone of metaseq.git on my system

### Environment

N/A to this issue

### Additional context

No additional context.

**Comment by hunterlang** [comment]
You can just change `fairinternal` to `facebookresearch`

**Comment by codeisnotcode** [comment]
Thanks. Issue resolved. (Wow, that was fast! Thanks!)
