### ISSUE TITLE
Training OPT-175B from scratch on 40GB A100 GPUs

### ISSUE THREAD

**Issue by chelseajohn** [facebookresearch/metaseq#210]
#### What is your question?
How can I train the OPT 175B model from scratch on 40GB A100 GPUS ?

#### What have you tried?
Tried to train the model on 192 A100 40GB GPU with model parallel of 8, but results in OOM errors 

#### What's your environment?
 - metaseq Version : [Forked Repo](https://github.com/chelseajohn/metaseq.git)  
 - PyTorch Version : 1.11.0
 - OS : Linux
 - Python version: Python 3.9.6
 - CUDA/cuDNN version: cuDNN/8.3.1.22-CUDA-11.5
 - GPU models and configuration: Each node contains 4 × NVIDIA A100 Tensor Core GPU with 40 GB; connected via NVLink3 to each other; [more info](https://apps.fz-juelich.de/jsc/hps/juwels/booster-overview.html)

**Comment by suchenzang** [comment]
@chelseajohn how large was your batch size?

**Comment by stephenroller** [comment]
That's indeed going to be pretty tough to train to completion. You probably need to lower the batchsize by a factor of 2, maybe even 4. You'll probably need to lower the LR to compensate.

**Comment by chelseajohn** [comment]
Thanks for replying ! 
I have tried various combinations of the following:
- Reduced the global batch size to M/8 and M/16 from M/4; where M = 1024*1024
- Tried with setting `ddp_bsz=1`
- Increased the `model_parallel` from 8 to 16

I was still not able to find a configuration that would work with 40GB A100's .

For the time being, the priority to find a working configuration for 175B model is lowered as we currently don't plan to continue using the OPT codebase. Therefore, I am closing this issue for now and might re-open in the future, if further assistance is required.
