### ISSUE TITLE
useless error message in model loading

### ISSUE THREAD

**Issue by mayank31398** [facebookresearch/metaseq#215]
Same error as in the issue https://github.com/facebookresearch/metaseq/issues/70

I am still getting this issue.
Local spawning is not working for 2.7B parameter model
I am not using any scheduler
This is the constants.py I am using:
```
# Copyright (c) Meta Platforms, Inc. and affiliates. All Rights Reserved.
#
# This source code is licensed under the MIT license found in the
# LICENSE file in the root directory of this source tree.

import os

MAX_SEQ_LEN = 2048
BATCH_SIZE = 2048  # silly high bc we dynamically batch by MAX_BATCH_TOKENS
MAX_BATCH_TOKENS = 3072
DEFAULT_PORT = 6010
MODEL_PARALLEL = 4
TOTAL_WORLD_SIZE = 4
MAX_BEAM = 16

try:
    # internal logic denoting where checkpoints are in meta infrastructure
    from metaseq_internal.constants import CHECKPOINT_FOLDER
except ImportError:
    # CHECKPOINT_FOLDER should point to a shared drive (e.g. NFS) where the
    # checkpoints from S3 are stored. As an example:
    # CHECKPOINT_FOLDER = "/example/175B/reshard_no_os"
    # $ ls /example/175B/reshard_no_os
    # reshard-model_part-0.pt
    # reshard-model_part-1.pt
    # reshard-model_part-2.pt
    # reshard-model_part-3.pt
    # reshard-model_part-4.pt
    # reshard-model_part-5.pt
    # reshard-model_part-6.pt
    # reshard-model_part-7.pt
    CHECKPOINT_FOLDER = "checkpoints"

# tokenizer files
BPE_MERGES = os.path.join(CHECKPOINT_FOLDER, "gpt2-merges.txt")
BPE_VOCAB = os.path.join(CHECKPOINT_FOLDER, "gpt2-vocab.json")
MODEL_FILE = os.path.join(CHECKPOINT_FOLDER, "reshard.pt")


LAUNCH_ARGS = [
    f"--model-parallel-size {MODEL_PARALLEL}",
    f"--distributed-world-size {TOTAL_WORLD_SIZE}",
    "--task language_modeling",
    f"--bpe-merges {BPE_MERGES}",
    f"--bpe-vocab {BPE_VOCAB}",
    "--bpe hf_byte_bpe",
    f"--merges-filename {BPE_MERGES}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--vocab-filename {BPE_VOCAB}",  # TODO(susanz): hack for getting interactive_hosted working on public repo
    f"--path {CHECKPOINT_FOLDER}/reshard.pt",
    "--beam 1 --nbest 1",
    "--distributed-port 13000",
    "--checkpoint-shard-count 1",
    "--use-sharded-state",
    f"--batch-size {BATCH_SIZE}",
    f"--buffer-size {BATCH_SIZE * MAX_SEQ_LEN}",
    f"--max-tokens {BATCH_SIZE * MAX_SEQ_LEN}",
    "/tmp",  # required "data" argument.
]

```

**Comment by badcode6** [comment]
still happening in ubuntu on wsl2
```
File "... .py", line 23, in <module>
    checkpoint = checkpoint_utils.load_model_ensemble_and_task(
  File "/home/..../.local/lib/python3.8/site-packages/metaseq/checkpoint_utils.py", line 554, in load_model_ensemble_and_task
    state = load_checkpoint_to_cpu(filename, arg_overrides)
  File "/home/.../.local/lib/python3.8/site-packages/metaseq/checkpoint_utils.py", line 489, in load_checkpoint_to_cpu
    paths_to_load = get_paths_to_load(local_path, suffix="shard")
  File "/home/.../.local/lib/python3.8/site-packages/metaseq/checkpoint_utils.py", line 429, in get_paths_to_load
    if not _is_checkpoint_sharded(checkpoint_files):
  File "/home/.../.local/lib/python3.8/site-packages/metaseq/checkpoint_utils.py", line 420, in _is_checkpoint_sharded
    size_ratio = max(sizes) / min(sizes)
ValueError: max() arg is an empty sequence```

**Comment by stephenroller** [comment]
This error comes when it is expecting files of one name and can't find them. Really it needs a better error message.

Can you check what paths it's trying to load and confirm they're correct for you?

**Comment by taesiri** [comment]
I had the same issue, and the problem was some missing files. Make sure you have `dict.txt`, `gpt2-merges.txt`, and `gpt2-vocab.json` in the same folder of the weights as described in [this link](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md#run-the-api).

You can get `dict.txt` from in [here](https://github.com/facebookresearch/metaseq/issues/19#issuecomment-1116386049).

It is also good to check the weight filenames to ensure they are in the correct format.

**Comment by badcode6** [comment]
> This error comes when it is expecting files of one name and can't find them. Really it needs a better error message.
> 
> Can you check what paths it's trying to load and confirm they're correct for you?

yes. i actually have it print out the path w/ `print(os.path.join(path, "vocab.json"))` and the file does exist (i did cat and then the path that pops out)

**Comment by badcode6** [comment]
> I had the same issue, and the problem was some missing files. Make sure you have `dict.txt`, `gpt2-merges.txt`, and `gpt2-vocab.json` in the same folder of the weights as described in [this link](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md#run-the-api).
> 
> You can get `dict.txt` from in [here](https://github.com/facebookresearch/metaseq/issues/19#issuecomment-1116386049).
> 
> It is also good to check the weight filenames to ensure they are in the correct format.

all 3 of these exist in the path such as the one used above. i can `cat` all 3 of them

**Comment by stephenroller** [comment]
Can you ls the directory for me?
