### ISSUE TITLE
Community Integration：Using OPT with Colossal-AI

### ISSUE THREAD

**Issue by binmakeswell** [facebookresearch/metaseq#228]
### Motivation

Thank you for your outstanding contribution to open OPT weights.

We have recently integrated OPT with the [Colossal-AI](https://github.com/hpcaitech/ColossalAI) system and would like to build a more formal integration with Metaseq.

Colossal-AI is a unified deep learning system for the big model era, which integrates many efficient techniques like multi-dimensional tensor parallelism, sequence parallelism, heterogeneous memory management, etc. 

By using Colossal-AI, we could help users to efficiently and quickly deploy large AI model training and inference, reducing large AI model budgets and scaling down the labor cost of learning and deployment.

### Pitch

Like the integration with [Hugging Face](https://github.com/facebookresearch/metaseq#using-opt-with--transformers) and [Alpa](https://github.com/facebookresearch/metaseq#using-opt-175b-with-alpa) community, we want to contribute to the use and deployment of OPT models with Colossal-AI, making less hardware resources for a more efficient and simple large-scale training and inference possible. 

We have provided an [example](https://github.com/hpcaitech/ColossalAI-Examples/tree/f743872c2089d6bb5e593db6a8a48d427e6b2b1e/language/opt) of OPT and Colossal-AI, with a corresponding [blog](https://medium.com/@yangyou_berkeley/colossal-ai-seamlessly-accelerates-large-models-at-low-costs-with-hugging-face-4d1a887e500d). A detailed tutorial will be added very soon. We can provide a draft PR for you to finish this integration and other necessary steps or content. We are also willing to assist you in any other way we can. 

Thank you for your review and look forward to your reply.

**Comment by suchenzang** [comment]
Hi @binmakeswell - Thanks for helping to build large-scale AI workload community! Happy to review any PRs sent over, but given our main goal of this codebase is to enable our ongoing research efforts, we generally won't accept code changes that require a lot of code changes to our core modules / classes (or add too much additional complexity with flags / configuration, as we already have issues on that front).

If there are measurable performance / efficiency gains, we will definitely be more inclined to test out and merge as needed.

**Comment by stephenroller** [comment]
Feel free as well to make a PR updating our README to point to your posts.
