### ISSUE TITLE
Make DATA_LOCATIONS for training easily configurable for external users

### ISSUE THREAD

**Issue by pragnakalpdev27** [facebookresearch/metaseq#236]
#### What is your question?
We are trying to train OPT-125m model for our custom dataset using Google Colab pro with one GPU.
Which files need to store in DATA_LOCATIONS?

#### Code

! python metaseq/launcher/opt_baselines.py \
  -n 1 -g 2 \
  -p test_v0 \
  --model-size 125m \
  --azure \
  --data /content/test_data \
  --checkpoints-dir "/content/ck_point" \
  --no-tensorboard \

#### What have you tried?
We are facing the below error while running the baseline command. We have updated path in metaseq/launcher/opt_job_constants.py file in below line:

DATA_LOCATIONS = { 
     ComputeEnvs.AZURE: "/data/opt", 
 } 

But we are facing an error as shown in below:

Traceback (most recent call last):
  File "/usr/local/bin/opt-baselines", line 33, in <module>
    sys.exit(load_entry_point('metaseq==0.0.1', 'console_scripts', 'opt-baselines')())
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/opt_baselines.py", line 337, in cli_main
    get_grid, postprocess_hyperparams, add_extra_options_func=add_extra_options_func
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/sweep.py", line 378, in main
    backend_main(get_grid, postprocess_hyperparams, args)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/slurm.py", line 34, in main
    grid = get_grid(args)
  File "/usr/local/lib/python3.7/dist-packages/metaseq-0.0.1-py3.7-linux-x86_64.egg/metaseq/launcher/opt_baselines.py", line 88, in get_grid
    raise RuntimeError("Where are you running this?! Check DATA_LOCATIONS.")
RuntimeError: Where are you running this?! Check DATA_LOCATIONS.

#### What's your environment?

  - metaseq Version (e.g., 1.0 or master): Forked Repo
 - PyTorch Version (e.g., 1.0) :  1.11.0
 - OS (e.g., Linux): Linux 
 - How you installed metaseq (`pip`, source): source
 - Build command you used (if compiling from source):
 - Python version: 3.7
 - CUDA/cuDNN version: cuda_11.1.TC455_06.29190527_0
 - GPU models and configuration: 1 Tesla p100
 - Any other relevant information:

**Comment by suchenzang** [comment]
We have this very unfortunate bit of hardcoding here, which you'll need to remove/edit as needed: https://github.com/facebookresearch/metaseq/blob/1c0048f15aa3f47ed568de76697eb0e8d37f0d6e/metaseq/launcher/opt_baselines.py#L84

We haven't spent any time making this easily configurable for external users - going to rename this issue and turn it into one to track fixing our data pathing configuration.

**Comment by Xirider** [comment]
Fixed in https://github.com/facebookresearch/metaseq/pull/443
