### ISSUE TITLE
Does the OPT support the task in Chinese?

### ISSUE THREAD

**Issue by jinxinglu** [facebookresearch/metaseq#274]

**Comment by stephenroller** [comment]
Sorry, can you provide more context?

**Comment by jinxinglu** [comment]
sorry, I should detail my question. I would like to know whether the chinese corpus is used in OPT training? I would like to test the performance of OPT in some concrete chinese question-answer tasks. thanks.

**Comment by stephenroller** [comment]
OPT was trained on roughly 99.8% English text. We have noticed it knows very rudimentary Chinese though.

**Comment by jinxinglu** [comment]
thanks very much!
