### ISSUE TITLE
Loading models

### ISSUE THREAD

**Issue by mrseeker** [facebookresearch/metaseq#28]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

I am trying to load the OPT models in a similar way as the fairseq models, but I seem to hit into quite some snags. Has anyone got a good example on how to load these models?

#### Code

```
from metaseq.models.transformer_lm import TransformerLanguageModel
model = TransformerLanguageModel.from_pretrained("./model_location")
```

#### What have you tried?
I have already tried various alternatives, but they always get the notification that the model could not get loaded, that it's missing something, etc.

#### What's your environment?

 - fairseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.11
 - OS (e.g., Linux): Linux
 - How you installed fairseq (`pip`, source): source
 - Build command you used (if compiling from source): pip install -e .
 - Python version: 3.9
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: Just wanting to load the weights for conversion.

**Comment by patrickvonplaten** [comment]
At HF we got the 350m checkpoint working ;-) 

https://github.com/patrickvonplaten/metaseq/blob/main/README.md#7-how-to-run-the-350-model

**Comment by mrseeker** [comment]
If that's the case, I can only assume a HF conversion is not far away? We (KoboldAI team) managed to convert fairseq models to XGLM, I can assume that's the same case here. From our experience, XGLM uses the same architecture as fairseq.

**Comment by hunterlang** [comment]
@patrickvonplaten how did you make`patrickvonplaten/opt_gpt2_tokenizer`? Is it just the default HF GPT2 tokenizer?

**Comment by patrickvonplaten** [comment]
@hunterlang, it's a GPT2Tokenizer that was loaded from the tokenizer files in https://github.com/facebookresearch/metaseq/tree/main/projects/OPT/assets

I.e. `patrickvonplaten/opt_gpt2_tokenizer` just contains those two files and then you can load it with our GPT2Tokenizer implemenation

**Comment by patrickvonplaten** [comment]
@hunterlang, it's a GPT2Tokenizer that was loaded from the tokenizer files in https://github.com/facebookresearch/metaseq/tree/main/projects/OPT/assets

I.e. `patrickvonplaten/opt_gpt2_tokenizer` just contains those two files and then you can load it with our GPT2Tokenizer implemenation

**Comment by Fengwills** [comment]
@patrickvonplaten I follow your code and readme, but I encountered Runtime error in Megatron-LM/megatron/initialize.py
at line 180 
` # Call the init process`
` torch.distributed.init_process_group(`
`        backend=args.distributed_backend,`
`        world_size=args.world_size, rank=args.rank,`
 `       timeout=timedelta(days=7))`
world_size = 1 rank = 0
# environment?
PyTorch Version: 1.10.1
OS : Linux
Build command you used (if compiling from source): pip install -e .
Python version: 3.7.7
CUDA/cuDNN version: 11.0
# command line
torchrun run_model.py --pipeline-model-parallel-size 1 --tensor-model-parallel-size 1


How can I load the model and run your code ?  many thanks

**Comment by patrickvonplaten** [comment]
Hey @Fengwills, 

Yeah we just commented out / removed this line of code in the Megatron repo

**Comment by Fengwills** [comment]
@patrickvonplaten
remove this line？ right？
`#Call the init process `
`torch.distributed.init_process_group(
backend=args.distributed_backend,
world_size=args.world_size, rank=args.rank,
timeout=timedelta(days=7))`

get a new bug, 
AssertionError: Default process group is not initialized

 seem to doesn' work for me, am I doing something wrong?

**Comment by stephenroller** [comment]
There is no way that getting around the process group init that will work.

I'm going to take a look at getting these models into vanilla, non-MP format but I have many pressing demands.

The sketch of the solution, if someone wants to implement, is to slightly modify the consolidate FSDP script to load flattened parameters and then peak inside the wrapper to get Non-flattened parameters (i.e. model.module.state_dict). The latest OPT readme shows how to use the consolidate script.

**Comment by patrickvonplaten** [comment]
Thanks for the hints here @stephenroller !

**Comment by rgzn-aiyun** [comment]
> Thanks for the hints here @stephenroller !

same problem.

**Comment by patrickvonplaten** [comment]
@suchenzang @stephenroller any way that you guys could send us or open-source the `param_metadata` dicts? 

I've tried for quite some time now to reproduce the correct parameter mapping without much success. 

It's not really stated on how many GPUs (`world_size` models other than 175B were trained), nor was I able to reproduce the parameter mapping. Also one thing I don't fully understand is why the two checkpoints

**Comment by stephenroller** [comment]
I think maybe some of these checkpoints were saved with use_sharded_state=False which means the checkpoints are pre-consolidated. The rank0 file would then be waaaay larger but rest would be just a few kb. This is the code path that results in shards with out that shard metadata field

**Comment by suchenzang** [comment]
Closing this given https://github.com/facebookresearch/metaseq/issues/88, https://github.com/facebookresearch/metaseq/issues/78, and https://github.com/facebookresearch/metaseq/issues/77, which should cover this issue as well.
