### ISSUE TITLE
Remove excess no_* checkpoint flags

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#324]
From https://github.com/facebookresearch/metaseq/pull/322: 

https://github.com/facebookresearch/metaseq/blob/414c32dfbc0789421aeceb6d979fb0f214e82dc1/metaseq/dataclass/configs.py#L514-L530

There's way too many of these here that aren't necessary. Clean this up.

**Comment by Xirider** [comment]
I looked through all the flags for creating checkpoints:

```
    save_interval: int = field(
        default=1, metadata={"help": "save a checkpoint every N epochs"}
    )
    save_interval_updates: int = field(
        default=0, metadata={"help": "save a checkpoint (and validate) every N updates"}
    )
    keep_interval_updates: int = field(
        default=-1,
        metadata={
            "help": "keep the last N checkpoints saved with --save-interval-updates"
        },
    )
    keep_last_epochs: int = field(
        default=-1, metadata={"help": "keep last N epoch checkpoints"}
    )
    keep_best_checkpoints: int = field(
        default=-1, metadata={"help": "keep best N checkpoints based on scores"}
    )
    no_save: bool = field(
        default=False, metadata={"help": "don't save models or checkpoints"}
    )
    no_epoch_checkpoints: bool = field(
        default=False, metadata={"help": "don't store checkpoints at epoch boundaries"}
    )
    no_last_checkpoints: bool = field(
        default=False, metadata={"help": "don't store last checkpoints"}
    )
    no_best_checkpoints: bool = field(
        default=False, metadata={"help": "don't store best checkpoints"}
    )
    no_save_optimizer_state: bool = field(
        default=False,
        metadata={"help": "don't save optimizer-state as part of checkpoint"},
    )
    no_save_optimizer_state_on_training_finished: bool = field(
        default=False,
        metadata={
            "help": "don't save optimizer-state as part of checkpoint when training is done"
        },
```

**Here are my suggestions:**

The following flags seem redundant:
no_save -> this is the same as just setting save_interval to 0
no_best_checkpoints -> should be the same as setting keep_best_checkpoints to 0
no_epoch_checkpoints -> the same as setting save_interval to 0 or - 1
(I would also make this more clean in the "help")

Here it might also make sense to rename save_interval to save_interval_epochs, to be more in line with save_interval_updates. The current naming is a bit confusing.

no_save_optimizer_state and no_save_optimizer_state_on_training_finished could be combined into a single positive flag "save_optimizer_state" with the options "all", "none”, “all_but_last” with the default “all”.


Please let me know what you think :)

**Comment by suchenzang** [comment]
@Xirider thanks for taking a look at this crufty task 😂 !!

So I actually think we can get rid of all the `no_*` flags for now, along with the `keep_*` flags too. Only thing we really care about is `save_interval` and `save_interval_updates` out of these.

Optimizer state can be stripped out after the fact - during training we want to always keep them around for restarts anyway.  

As for save_interval -> save_interval_epochs.... yeah why not. Epoch sometimes doesn't really mean what we normally think it means (https://github.com/facebookresearch/metaseq/issues/198), which is also our own fault, so it's fine to leave it confusing here since total confusion around this meaning will probably still remain the same after a rename, lol.  I don't have a preference here at all.

**Comment by Xirider** [comment]
I see! In that case I'll remove all the `no_*` and `keep_*` flags and clean up their logic.
For save_interval -> save_interval_epochs: I'll just keep it as it is now and add some info about epochs meaning shards 😄
