### ISSUE TITLE
[Paper][Dialogue] How to normalize perplexities to be in the space of the GPT-2 tokenizer?

### ISSUE THREAD

**Issue by heya5** [facebookresearch/metaseq#325]
#### What is your question?
I read your paper, which mentions the following in section 3.2:
> To control for different tokenization in each of the models, we normalize all perplexities to be in the space of the
GPT-2 tokenizer.

Does this mean that you re-pretrained the other models in Table 2 **with gpt2 tokenizer?**
![image](https://user-images.githubusercontent.com/27731754/187488097-53aa13e3-3bc8-48c0-b1ef-d2ef77234a64.png)

**Comment by stephenroller** [comment]
PPL = exp(sum(NLL loss) / num_tokens))

NLL loss is over the entire sequence, and doesn't care about the number of tokens.

Therefore we can convert PPL's of different dictionaries by keeping the same NLL loss and dividing by the number of tokens in the target dictionary.

Doesn't work for UNKs etc, but those don't exist in modern tokenizers.
