### ISSUE TITLE
add web demo/model to Huggingface

### ISSUE THREAD

**Issue by AK391** [facebookresearch/metaseq#33]
Hi, would you be interested in adding metaseq to Hugging Face? The Hub offers free hosting, and it would make your work more accessible and visible to the rest of the ML community. Models/datasets/spaces(web demos) can be added to a user account or organization similar to github.

there is already a facebook research organization on Huggingface with spaces: https://huggingface.co/facebook

Example spaces with repos:
github: https://github.com/salesforce/BLIP
Spaces: https://huggingface.co/spaces/salesforce/BLIP

github: https://github.com/facebookresearch/omnivore
Spaces: https://huggingface.co/spaces/akhaliq/omnivore

Example from other organizations:
Keras: https://huggingface.co/keras-io
Microsoft: https://huggingface.co/microsoft

and here are guides for adding spaces/models/datasets to your org

How to add a Space: https://huggingface.co/blog/gradio-spaces
how to add models: https://huggingface.co/docs/hub/adding-a-model
uploading a dataset: https://huggingface.co/docs/datasets/upload_dataset.html

Please let us know if you would be interested and if you have any questions, we can also help with the technical implementation.

**Comment by younesbelkada** [comment]
Hi!
FYI, there is a WIP PR to port these models on `transformers` library. https://github.com/huggingface/transformers/pull/17088 
Feel free to jump in and help us merge the PR :-) !
If we successfully merge the PR, it would be super easy to deploy these models on HuggingFace spaces for eg

**Comment by suchenzang** [comment]
Would love for someone to take this on! Looks like the above PR is already out. Whoever wants to own this issue should self-assign :)

**Comment by stephenroller** [comment]
Significant progress has been made in #88.

**Comment by suchenzang** [comment]
Closing this given https://github.com/facebookresearch/metaseq/issues/88 - HF progress to be tracked there.

**Comment by StatsGary** [comment]
Waiting with interest on this.
