### ISSUE TITLE
Delete Heartbeat Timeout

### ISSUE THREAD

**Issue by stephenroller** [facebookresearch/metaseq#336]
Heartbeat timeout is no longer necessary. It's since replaced by simple use of the `NCCL_ASYNC_ERROR_HANDLING=1` environmental variable.

Let's clean up this dead code.

**Comment by stephenroller** [comment]
Replaced by setting environmental variable `NCCL_ASYNC_ERROR_HANDLING=1`

**Comment by annavordou** [comment]
May I issue a pull request for my changes?

**Comment by stephenroller** [comment]
Yes, please do!

**Comment by annavordou** [comment]
I've issued a PR about this and I would appreciate any feedback

**Comment by stephenroller** [comment]
I'm sorry, I don't see any PR. Can you link to it? Are you sure it's not only in your private fork?

**Comment by annavordou** [comment]
How about now?
I did had a problem with signing up to CLA though but I don't know if it is an issue.

**Comment by annavordou** [comment]
I fixed the problem with CLA so please ensure me that everything is fine.

**Comment by suchenzang** [comment]
Done via https://github.com/facebookresearch/metaseq/pull/364 - thanks @annavordou !
