### ISSUE TITLE
As usual, not an open license

### ISSUE THREAD

**Issue by deemeetree** [facebookresearch/metaseq#34]
In the best traditions of Facebook, you're offering this model under a license that makes it impossible to use it for commercial projects. Which, in turn, means that nobody will have the scale to turn it into something useful. 

Well done, Facebook, as usual, you show your real face.

In addition to your non-existent customer support for users and advertisers.

I really hope that one day your company goes bankrupt, so you give space to somebody who truly cares. The culture at Facebook is rotten.

**Comment by puffy310** [comment]
Is anyone's company owned research lab really a good actor? Ah yes misusing the word "open" again. EleutherAI said they'd stop making bigger LLMs. I guess they'll be back at it... good thing for Huggingface. Not hating on anyone but yeah this is what hacker collectives are for.

**Comment by stephenroller** [comment]
Please refer to [our whitepaper](https://arxiv.org/abs/2205.01068) for extensive discussion of why we believe this technology is not ready for commercial applications.

**Comment by puffy310** [comment]
I think that's pretty fair we don't mean to harass your team. Respect to you! :)) have a great rest of your day.
