### ISSUE TITLE
Python package location issue during setup

### ISSUE THREAD

**Issue by auwsom** [facebookresearch/metaseq#347]
Hi, I have a some kind of problem with installing Metaseq on Ubuntu Jelly. It looks like some packages are installing in place where the ./run.sh script for running the OPT-2.7B model following this guide: https://www.pragnakalp.com/exploring-the-text-generation-with-opt-open-pre-trained-transformers/ and I've tried uninstalling metaseq and reinstalling following the current official repo here: https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md. I'm using a virtual env.

Basically when running ./run.sh I get this error: "ImportError: cannot import name 'data_dir' from 'helpers' (/home/user/.local/lib/python3.10/site-packages/helpers/__init__.py)". If I instead use sudo with `sudo pip3 install -e .`, I get a warning about installing as root but this error goes away. This suggests to me that Helpers is installed in a directory only accessible by root, though this is the first time I installed a pip package with sudo.

So I tried reinstalling with no sudo and I get a couple of warnings/errors: "Defaulting to user installation because normal site-packages is not writeable" and "[Errno 13] Permission denied: '/usr/local/lib/python3.10/dist-packages/test-easy-install-294163.write-test'"

So I try rolling with it and run ./run.sh as sudo but then get "ModuleNotFoundError: No module named 'torch._C'", even though `pip show torch` reports "Version: 1.12.1+cu116" at /home/user/.local/lib/python3.10/site-packages. (a user install location, not root).

I'm trying some other LLM installs, but wanted to report here in case either there is a simple fix, or others run into the same issue. Thanks

**Comment by auwsom** [comment]
I also have this error right below the Errno 13: "The installation directory you specified (via --install-dir, --prefix, or  the distutils default setting) was:  /usr/local/lib/python3.10/dist-packages/"

This suggests to me that maybe the Helper install was directed toward /usr/local... which are owned by root and have 755 permissions not allowing write by non-root. This may be from CIS hardening, but could also be Ubuntu default. If its the former, its important to keep. Maybe setup.py needs to install to the other user install location above.

**Comment by stephenroller** [comment]
I recommend installing metaseq in a virtualenv or a condaenv to avoid dealing with conflicts with system python.

I'm not even sure where we would "import helpers" directly or indirectly 😅

**Comment by auwsom** [comment]
Hi @stephenroller , thanks for the reply. 

I did install in a venv as mentioned above. The error calling Helpers is traced to this file first in the error message: "/home/user/.local/lib/python3.10/site-packages/metaseq/__init__.py" then "/home/user/.local/lib/python3.10/site-packages/helpers/init.py"
