### ISSUE TITLE
E2E tests for training resumption

### ISSUE THREAD

**Issue by ruanslv** [facebookresearch/metaseq#351]
## 🚀 Feature Request
Adding tests for restarting a training run after some interruption

### Motivation
Restoring training runs from checkpoints is a critical feature for large-scale models and has multiple steps, including downloading checkpoint from blob storage, loading the data to the correct token, storing checkpoints after some conditions are met, etc.

Tests would allow us to safe-guard this critical flow in case of potential broken changes.

### Pitch

A CI test that trains a small model, stores a checkpoint file to blob, downloads that checkpoint file and successfully continues the training run.

### Alternatives

Unit-tests that cover each step separately.

### Additional context

https://github.com/facebookresearch/metaseq/commit/e3ea5070a8c1bae77703aef7fc0f5537bd437963 -- this commit caused some checkpoint files to stop being stored.

**Comment by Xirider** [comment]
I would like to work on this.

**Comment by suchenzang** [comment]
@Xirider As a heads up: you'll probably have to mock out the blob storage bit (implicitly testing our checkpointing logic too), so this would be quite involved (related issues: https://github.com/facebookresearch/metaseq/issues/268 and https://github.com/facebookresearch/metaseq/issues/142)
