### ISSUE TITLE
Update setup documentation for latest master

### ISSUE THREAD

**Issue by roywei** [facebookresearch/metaseq#390]
## 📚 Documentation

Hi I came from this comment:
https://github.com/facebookresearch/metaseq/pull/349#issuecomment-1269519987

Looks like the setup docs need to be updated to use latest master.
https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md

Could you share which branch to use now or update the `prefetch_fsdp_params_simple` branch?

Also any reason to use a pinned commit of apex?
`git checkout e2083df5eb96643c61613b9df48dd4eea6b07690`
I've tried apex master, it also seems to work.

Happy to raise a PR if you can point me to the right versions.

Thanks!!

**Comment by suchenzang** [comment]
Hi @roywei ! Can you try switching to latest main and see if that works for you? `process_group_reduce_scatter` was brought into main via https://github.com/facebookresearch/fairscale/pull/897

**Comment by roywei** [comment]
Hi, thanks for the pointer! cherry-pick https://github.com/facebookresearch/fairscale/pull/897 on top of `prefetch_fsdp_params_simple` works with latest master.

`main` branch of  `fairscale` still does not work with metaseq

There are several import errors I was able to fix, but stuck later at this assertion error:
```assert isinstance(model, FSDP), "expected model to already be wrapped in FSDP"```

Any way I have a working combination now. Thanks!
