### ISSUE TITLE
streaming_finetune_language_modeling broken in latest main

### ISSUE THREAD

**Issue by jxmsML** [facebookresearch/metaseq#396]
## 🐛 Bug

On the latest metaseq main, my training cmd with task=streaming_finetune_language_modeling is broken with AttributeError like
```
"/private/home/jingxu23/src_metaseqpy38_20220328/metaseq/metaseq/checkpoint_utils.py", line 88, in save_checkpoint
    extra_state = {"train_iterator": epoch_itr.state_dict(), "val_loss": val_loss}
  File "/private/home/jingxu23/src_metaseqpy38_20220328/metaseq/metaseq/data/iterators.py", line 289, in state_dict
    f"Saving state_dict so we can skip workers quickly: {len(dataset.len_cache.data)} "
  File "/private/home/jingxu23/.conda/envs/metaseqpy38_20220328/lib/python3.8/site-packages/torch/utils/data/dataset.py", line 226, in __getattr__
    raise AttributeError
```
Here dataset = `StreamingSrcTgtDataset` without the attr `len_cache`, as in [streaming_finetune_language_modeling](https://github.com/facebookresearch/metaseq/blob/main/metaseq/tasks/streaming_finetune_language_modeling.py#L102)
The root cause (my guess) seems to be that after #352, dataset is changed from `StreamingSrcTgtDataset` -> `DocumentToSequenceDataset` within `streaming_language_modeling` (parent of `streaming_finetune_language_modeling`), and yet there are other logics that **only work** for `DocumentToSequenceDataset`.

**Comment by suchenzang** [comment]
@jxmsML I think this should be fixed now - can you confirm?

**Comment by suchenzang** [comment]
Should be fixed via https://github.com/facebookresearch/metaseq/pull/398 - please reopen if you still see issues!
