### ISSUE TITLE
91$

### ISSUE THREAD

**Issue by 91CH** [facebookresearch/metaseq#41]
### To Reproduce

Steps to reproduce the behavior (**always include the command you ran**):

1. Run cmd '....'
2. See error

### Environment

 - fairseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed fairseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by suchenzang** [comment]
Please add more details for what this bug report is supposed to cover, and we can reopen.
