### ISSUE TITLE
BB3 30B model reshard problem

### ISSUE THREAD

**Issue by luyunan0404** [facebookresearch/metaseq#425]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?
I'm trying to run bb3 with 30B model, but there are some problem in starting metaseq API. 
I follow the steps as following:
<img width="1027" alt="Screen Shot 2022-10-16 at 4 09 42 PM" src="https://user-images.githubusercontent.com/43186578/196056533-695b5fc0-8866-44a9-b04c-d1ce49596116.png">

It output the following error:
<img width="1210" alt="Screen Shot 2022-10-16 at 4 26 10 PM" src="https://user-images.githubusercontent.com/43186578/196056578-8f737446-4915-46a6-84ea-2aae71b08e7c.png">

I know that my reshard.pt doesn't exist, but my file format in the resharded folder are the same format as the code sample in your constant.py file, so I was wondering how to set it up correctly?
<img width="689" alt="Screen Shot 2022-10-16 at 4 29 56 PM" src="https://user-images.githubusercontent.com/43186578/196056745-8ce98ed5-e09b-4a68-b439-edc68ef87739.png">
<img width="711" alt="Screen Shot 2022-10-16 at 4 33 57 PM" src="https://user-images.githubusercontent.com/43186578/196056935-ae7c8711-6451-4447-9856-146d1fc10b63.png">

**My final target is to make this bb3 30B model works no matter in which ways!**

#### What have you tried?
I tried 2 ways:
1.  Reshard again according to your API docs, with SHARDED_MODEL_PATH=/home/lyn/ParlAI/data/models/bb3/resharded, checkpoint_last=reshard, RESHARDED_PATH=/home/lyn/ParlAI/data/models/bb3/resharded2, MODEL_PARALLEL=4

I have do some changes already:
<img width="1008" alt="Screen Shot 2022-10-16 at 5 03 20 PM" src="https://user-images.githubusercontent.com/43186578/196058371-ad0057fe-65d3-4e02-8860-4a5c32196e7e.png">

But it still not working, there is no key "shard_metadata" in state.
<img width="1428" alt="Screen Shot 2022-10-16 at 5 02 07 PM" src="https://user-images.githubusercontent.com/43186578/196058141-039a69eb-4d27-4286-9c5b-8378ba7d2570.png">

2. Instead of using 4 resharded files, I directly use consolidated.pt as the CHECKPOINT_folder
<img width="1196" alt="Screen Shot 2022-10-16 at 5 14 04 PM" src="https://user-images.githubusercontent.com/43186578/196058616-5a210ede-82a4-49ec-82ce-87402a6a86fb.png">
However, I have already installed Megatron-LM according to your set-up instruction. I'm not sure how to check it whether it really works or not.

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): master
 - PyTorch Version (e.g., 1.0): 1.12
 - OS (e.g., Linux): Ubuntu 22.04
 - How you installed metaseq (`pip`, source): source
 - Build command you used (if compiling from source): like your setup information
(git clone https://github.com/facebookresearch/metaseq.git
cd metaseq
pip3 install -e .
# turn on pre-commit hooks
pre-commit install)
 - Python version: 3.9
 - CUDA/cuDNN version: 11.6
 - GPU models and configuration: AWS gdn4x12 (so it should be 4 T4 GPU with 16G memory for each)
 - Any other relevant information:

**Comment by luyunan0404** [comment]
Hi, is there any updates?

**Comment by tangbinh** [comment]
@luyunan0404 I think this issue might be related to the initialization of distributed processes (see the discussion in #407). Can you try removing the `--distributed-port` option from your configs in `constants.py`?

**Comment by luyunan0404** [comment]
Hi @tangbinh , thanks for your answers on this reshard problem, it doesn't report that issue anymore. But how should I change the constant MODEL_FILE? Since I have reshard it to reshard-model_part-<0/1/2/3>.pt.
<img width="699" alt="Screen Shot 2022-11-04 at 12 05 19 PM" src="https://user-images.githubusercontent.com/43186578/200022578-84e52069-5af0-4a7d-adf6-059ef429babf.png">


Then, when I directly run the "metaseq-api-local", the debug information print the following out, I'm not sure whether it is correct? It "loading model(s) from /home/lyn/ParlAI/data/models/bb3/resharded/reshard.pt" which doesn't exist actually. I don't know whether it will automatically loading <0/1/2/3> reshard file or not?
<img width="1430" alt="Screen Shot 2022-11-04 at 3 02 38 PM" src="https://user-images.githubusercontent.com/43186578/200055773-9c8ec11a-cd29-4cb5-8aca-e5e1ce549e57.png">

Because after this , it popup out of memory problem. I'm using AWS Ubuntu 22.04 with 4xT4 GPU for this project. I check the status of GPU during running "metaseq-api-local". At first, it uses ~500M memory per GPU, then it suddenly put all the burden on 1 GPU as below with other process being killed(I think).

<img width="714" alt="Screen Shot 2022-11-04 at 3 13 52 PM" src="https://user-images.githubusercontent.com/43186578/200056901-7ac7e2cb-5a72-46e5-ae66-fca73d9f96f3.png">

<img width="720" alt="Screen Shot 2022-11-04 at 3 16 11 PM" src="https://user-images.githubusercontent.com/43186578/200057446-50b5ccf9-4425-4d5b-80df-d39b58bda2ef.png">

<img width="718" alt="Screen Shot 2022-11-04 at 3 16 31 PM" src="https://user-images.githubusercontent.com/43186578/200057502-657b543e-577e-4495-8880-3b11ff216d29.png">


The full error log is as below:
<img width="1428" alt="Screen Shot 2022-11-04 at 3 27 01 PM" src="https://user-images.githubusercontent.com/43186578/200059169-be20e846-f1d8-4eb5-913f-0472d67ef136.png">
<img width="1433" alt="Screen Shot 2022-11-04 at 3 27 33 PM" src="https://user-images.githubusercontent.com/43186578/200059257-aaaf9716-07ab-430e-8888-75c1999fda0d.png">


The settings I change in constant.py file is as below:
MODEL_PARALLEL = 4
TOTAL_WORLD_SIZE = 4
CHECKPOINT_FOLDER = "/home/lyn/ParlAI/data/models/bb3/resharded"
![image](https://user-images.githubusercontent.com/43186578/200058347-de7e23ae-3786-4c06-96f7-40c48be6c4f4.png)

Thanks very much for your help!

**Comment by luyunan0404** [comment]
If everything looks normal to you, I can change the setting to include 8 GPU (it will take some time so I want to make sure everything I did is correct), but I was concerning about setting sth wrong lead it only use 1 GPU instead of full power from 4 GPU at some point. Besides, from the instructions here( https://github.com/facebookresearch/ParlAI/tree/main/projects/bb3#bb3-30b175b-interact), for 30B model, it need 56GB memory. In this case, I think 4 x T4 (4x16GB) should be able to work?

**Comment by tangbinh** [comment]
> But how should I change the constant MODEL_FILE? 

@luyunan0404 Your `MODEL_FILE` config looks good to me. It's expected that the path `/home/lyn/ParlAI/data/models/bb3/resharded/reshard.pt` doesn't exist since we add the suffix (e.g. `model_part-0.pt`) when trying to load the resharded checkpoints (e.g. `reshard-model_part-0.pt`).

Each resharded checkpoint is 15013006536 bytes or 14.3 GB, so it might not fit into a single 16GB GPU. You might want to try some GPUs with more memory or reshard the checkpoints into more model parallel parts before loading them.

**Comment by luyunan0404** [comment]
Thanks very much for your help! I'm using 8 GPU and It's working now!
