### ISSUE TITLE
Remove Fixed LR scheduler references

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#434]
There's a few places in our codebase where we hack in an override to a fixed LR scheduler:

https://github.com/facebookresearch/metaseq/blob/37809ec65632c434ed722a5c8aa37cd194ce9f8b/metaseq/dataclass/utils.py#L400-L403

https://github.com/facebookresearch/metaseq/blob/37809ec65632c434ed722a5c8aa37cd194ce9f8b/metaseq/options.py#L151-L153

We should remove these references entirely and fix the origin of this hack, which likely is coming from the registry setup: https://github.com/facebookresearch/metaseq/blob/37809ec65632c434ed722a5c8aa37cd194ce9f8b/metaseq/optim/lr_scheduler/__init__.py#L21 (but still to be confirmed)

**Comment by andrewPoulton** [comment]
Just a note @Xirider - I'm planning to change the default lr scheduler as a fix in #429 (to inverse sqrt). I haven't confirmed that that's the source of the hacks, mind.

**Comment by Xirider** [comment]
@andrewPoulton Do you have any updates on this?

**Comment by andrewPoulton** [comment]
Sorry, got bogged down elsewhere - I think we can make inverse sqrt the new default, so my PR won't be a blocker here.

**Comment by Xirider** [comment]
Thanks!
