### ISSUE TITLE
load_state_dict error when loading from MP models resharded from a singleton

### ISSUE THREAD

**Issue by jxmsML** [facebookresearch/metaseq#442]
## ❓ Questions and Help
I'm running interactive_cli on a reshard.pt with (resharded from a singleton consolidated file) and notice the model has a load_state error (missing `qkv_proj.weight`, 'qkv_proj.bias`): model is `transformer_lm_megatron`, but in the consolidated.pt the `state['model']` has the unconcatenated states `q_proj`, `k_proj`, `v_proj` (saved when consolidating the original fsdp models into a singleton) https://github.com/facebookresearch/metaseq/blob/4629c56c467c1c40ef518a86f12799062e2551fa/metaseq/distributed/stitch_fsdp_ckpt.py#L287-L290)

I then notice that Alpa has the same [renaming logic](https://github.com/alpa-projects/alpa/blob/7da1e69b2ca65a1e46dafa183c3d4491a1cbdb33/examples/llm_serving/scripts/step_2_consolidate_992_shards_to_singleton.py#L397-L400). However, they [concatenate](https://github.com/alpa-projects/alpa/blob/04d7e73118d302bb0ee6caeaa8e532b72a846091/examples/llm_serving/model/opt_model.py#L681)  the `q_proj`, `v_proj`, `k_proj` into `qkv_proj` when loading from `consolidated.pt` singleton file.

So far I can't find such logic of concatenating the `q_proj`, `v_proj`, `k_proj` into `qkv_proj` in metaseq. 

### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by tangbinh** [comment]
@jxmsML The `qkv_proj` can be found in [ModelParallelMultiheadAttention](https://github.com/facebookresearch/metaseq/blob/f2cd36798793604cf51ab8b8a2cb167c964f9667/metaseq/model_parallel/modules/multihead_attention.py#L185), which is [enabled by default](https://github.com/facebookresearch/metaseq/blob/f2cd36798793604cf51ab8b8a2cb167c964f9667/metaseq/model_parallel/modules/multihead_attention.py#L91) when used with Megatron. This is in contrast with the individual `q_proj`, `k_proj`, `v_proj` in [MultiheadAttention](https://github.com/facebookresearch/metaseq/blob/f2cd36798793604cf51ab8b8a2cb167c964f9667/metaseq/modules/multihead_attention.py#L21). The conversion you referred to in [`stitch_fsdp_ckpt`](https://github.com/facebookresearch/metaseq/blob/4629c56c467c1c40ef518a86f12799062e2551fa/metaseq/distributed/stitch_fsdp_ckpt.py#L287-L290) makes sense to me as we need to convert the former attention into the latter when consolidate MP shards into one singleton.

I presume we need to reverse the effects when going from the singleton checkpoint to MP shards. Would you mind sharing how you did the resharding from the singleton checkpoint?

**Comment by tangbinh** [comment]
> So far I can't find such logic of concatenating the q_proj, v_proj, k_proj into qkv_proj in metaseq.

I think the weights are concatenated by default for `ModelParallelTransformerLanguageModel`, and we occasionally split them to support `TransformerLanguageModel`, which doesn't have MP (e.g. see [stitch_fsdp_ckpt](https://github.com/facebookresearch/metaseq/blob/4629c56c467c1c40ef518a86f12799062e2551fa/metaseq/distributed/stitch_fsdp_ckpt.py#L287-L290)). After some recent code refactoring, we only support `ModelParallelTransformerLanguageModel` now, so you can safely assume that the KVQ weights are always together.

If for some reason you have some checkpoints with separate `q_proj`, `k_proj`, `v_proj` weights, they can be merged together quite easily, e.g. 
```python
for key in list(state['model'].keys()):
    if "k_proj" in key:
        kvq = torch.cat([state["model"][key], state["model"][key.replace("k_proj", "v_proj")], state["model"][key.replace("k_proj", "q_proj")]], dim=0)
        state["model"][key.replace("k_proj", "qkv_proj")] = kvq
        state["model"].pop(key)
        state["model"].pop(key.replace("k_proj", "v_proj"))
        state["model"].pop(key.replace("k_proj", "q_proj"))
```

It's been a while without any update, so I'm closing the issue now. Please let us know if you need further help.
