### ISSUE TITLE
sequence_generator forward decoder not model

### ISSUE THREAD

**Issue by jxmsML** [facebookresearch/metaseq#444]
## ❓ Questions and Help
This is probably very tiny, but why is this that SequenceGenerator._generate only call `self.model.decoder(src_tokens, **kwargs)` instead of `self.model(src_tokens, **kwargs)` https://github.com/facebookresearch/metaseq/blob/4629c56c467c1c40ef518a86f12799062e2551fa/metaseq/sequence_generator.py#L169-L172

The reason I asked is this is probably not friendly for arch where model is a wrapper of Decoder + something else.

 
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by tangbinh** [comment]
Please see the fix in #700.
