### ISSUE TITLE
PathManager has no attribute `supports_rename`

### ISSUE THREAD

**Issue by andrewPoulton** [facebookresearch/metaseq#477]
## 🐛 Bug

Following #441, a regression occurs when running `metaseq/launcher/opt_baselines.py`, due to the call to `PathManager.supports_rename` on L536 in `checkpoint_utils.py`, but this attribute no longer exists after #441 was merged.

### To Reproduce

Run (eg from @Xirider)
```
python metaseq/launcher/opt_baselines.py --prefix train.8m --model-size 8m --checkpoints-dir ./test-checkpoint --tensorboard-logdir ./test-checkpoint --num-trials 1 --azure --num-gpus 4 --num-nodes 1 --seed 1 --circleci --local --disable-validation --max-epoch 100 --max-update 100
```

**Comment by davides** [comment]
Closing as the fix was merged in https://github.com/facebookresearch/metaseq/pull/478
