### ISSUE TITLE
Missing megatron.mpu attribute LinearWithGradAccumulationAndAsyncCommunication in metaseq

### ISSUE THREAD

**Issue by dkey-amazon** [facebookresearch/metaseq#496]
## 🐛 Bug

Getting an error using the latest version of metaseq to train an OPT model.  It seems like `metaseq/model_parallel/models/transformer.py` may be using a `megatron.mpu` feature that is not yet available on the `fairseq_v2` branch of [Megatron-LM](https://github.com/ngoyal2707/Megatron-LM)?

The change came from [PR #460](https://github.com/facebookresearch/metaseq/pull/460).  I was able to work around the issue by checking out the metaseq repo to commit `ce294a115cecf02efb8bae2f26305728d7c05500` (the commit before PR #460 was merged).  Not a perfect fix, but it unblocked me for now.

Error Log:
```
Traceback (most recent call last):
...
  File ".../metaseq/model_parallel/models/transformer.py", line 65, in output_layer
    x = mpu.LinearWithGradAccumulationAndAsyncCommunication.apply(
AttributeError: module 'megatron.mpu' has no attribute 'LinearWithGradAccumulationAndAsyncCommunication'

```

Is there another branch or commit I should use that will work around this issue?  Does the new code change need to be reverted?  Please let me know if I can help or provide any further details.  Thanks!

**Comment by punitkoura** [comment]
I think you might need to update your megatron-LM branch? To fairseq_v3 instead of fairseq_v2
https://github.com/facebookresearch/metaseq/blob/5ca6005552b7a049f071754393d5b86185e0db6a/.circleci/config.yml#L49

**Comment by dkey-amazon** [comment]
Looks like updating [Megatron-LM](https://github.com/ngoyal2707/Megatron-LM) to branch `fairseq_v3` fixed my issues.  Closing this bug.  Thanks!
