### ISSUE TITLE
Issue running reshard_mp_launch.sh

### ISSUE THREAD

**Issue by mahdi-b** [facebookresearch/metaseq#50]
Running the recently added reshard_mp_launch.sh on the 992 shard downloaded generated an an error.

### To Reproduce
Running :
```
bash metaseq/scripts/reshard_mp_launch_no_slurm.sh model/checkpoint_last  metaseq_model_combined/ 8 1
```
generates the following:

```
python -m metaseq.scripts.reshard_mp model/checkpoint_last metaseq_model_combined/ --part 7 --target-ddp-size 1
reshard_mp7_ddp1
Waiting on jobs...


metaseq/scripts/reshard_mp_launch_no_slurm.sh: line 24: 423467 Killed                  python3 -m metaseq.scripts.reshard_mp $prefix $save_dir --part $i --target-ddp-size $tgt_size
metaseq/scripts/reshard_mp_launch_no_slurm.sh: line 24: 423469 Killed                  python3 -m metaseq.scripts.reshard_mp $prefix $save_dir --part $i --target-ddp-size $tgt_size
metaseq/scripts/reshard_mp_launch_no_slurm.sh: line 24: 423472 Killed                  python3 -m metaseq.scripts.reshard_mp $prefix $save_dir --part $i --target-ddp-size $tgt_size
Saving to metaseq_model_combined//reshard-model_part-1-shard[i].pt: 1it [01:42, 102.60s/it]
Saving to metaseq_model_combined//reshard-model_part-4-shard[i].pt: 1it [01:42, 102.01s/it]
Saving to metaseq_model_combined//reshard-model_part-7-shard[i].pt: 1it [01:42, 102.16s/it]
Saving to metaseq_model_combined//reshard-model_part-6-shard[i].pt: 1it [01:45, 105.07s/it]
metaseq/scripts/reshard_mp_launch_no_slurm.sh: line 24: 423470 Killed                  python3 -m metaseq.scripts.reshard_mp $prefix $save_dir --part $i --target-ddp-size $tgt_size
Done
```

Note that running the command output by `reshard_mp_launch.sh`; sample command listed below, seems to work  and generates the files `reshard-model_part-0-shard0.pt` through `reshard-model_part-7-shard0.pt`

Sample command ran manually:
python -m metaseq.scripts.reshard_mp model/checkpoint_last metaseq_model_combined/ --part 0 --target-ddp-size 1

**Comment by stephenroller** [comment]
Probably there isn't enough memory to run all jobs in parallel.

**Comment by mahdi-b** [comment]
@stephenroller thanks for the suggestion, but watching free memory shows that there is about 170GB when the program crashes. Also,  across different runs, at least 4 out of 8 shared complete successfully. One run had 6 out of 8 complete successfully. This is not critical as I am able to run the programs manually but thought I should report it.

**Comment by suchenzang** [comment]
Closing this given https://github.com/facebookresearch/metaseq/issues/88, https://github.com/facebookresearch/metaseq/issues/78, and https://github.com/facebookresearch/metaseq/issues/77, which should cover this issue as well.
