### ISSUE TITLE
How long does it take to apply for the OPT-175B model ?

### ISSUE THREAD

**Issue by Hao-Tju** [facebookresearch/metaseq#560]
About three weeks ago, I submitted an application for the OPT-175B model. And I haven't received any messages from the community or the developer team. Does anyone know how long it will take to get the result? Thanks in advance.

**Comment by kamalkraj** [comment]
Same here

**Comment by suchenzang** [comment]
@Hao-Tju @kamalkraj another batch of approvals will be going out today
