### ISSUE TITLE
Any plan for intergrating OPT-IML to huggingface? 

### ISSUE THREAD

**Issue by linmou** [facebookresearch/metaseq#580]
## 🚀 Feature Request

Thanks for your great work on OPT-IML, a solid step to open-sourced AGI. But OPT-IML is unavailable on huggingface hub till now, which hinders its further application. Is there any plan to push it to huggingface ?

**Comment by sriniiyer** [comment]
Thanks @linmou. We are working on making the 30B model available on huggingface, which should be available in a couple of days to a week + releasing models of other sizes too! Stay tuned!

**Comment by lyy1994** [comment]
@sriniiyer Hi, may I know when OPT-IML Bench (the dataset for instruction fine-tuning OPT) will be available publically?

**Comment by upwindflys** [comment]
I also want to know when it can be available publically?

**Comment by sriniiyer** [comment]
30B models should be available on huggingface now.

**Comment by xiangjjj** [comment]
Thank you!

**Comment by upwindflys** [comment]
Thanks!
