### ISSUE TITLE
Unify `transformer_lm_megatron` and `transformer_lm` arch

### ISSUE THREAD

**Issue by suchenzang** [facebookresearch/metaseq#583]
In the process of unifying model-parallel codepaths (https://github.com/facebookresearch/metaseq/issues/389), we should remove the two different arch definitions.

**Comment by bashnick** [comment]
**Short summary:**
Unified code paths:
- unified codepaths for model-parallel and non-model-parallel: removed the model_parallel path and merged it into models file path

Simplified inheritance layers:
- removed TransformerDecoder -> ModelParallelTransformerDecoder
- removed LanguageModel -> BaseModel
- removed TransformerDecoderLayer -> ModelParallelTransformerDecoderLayer
- removed MultiheadAttention -> ModelParallelMultiheadAttention
- removed arch transformer_lm -> transformer_lm_megatron

Updated tests accordingly:
- updated test gpu_tests/test_hf_compatibility.py to work with model_parallel
