### ISSUE TITLE
What is the difference between "fairseq" and "opt"?

### ISSUE THREAD

**Issue by justlearntutors** [facebookresearch/metaseq#585]
### Before asking:   
1. search the issues.   
2. search the docs.    

#### What is your question?

What is the difference between "fairseq" and "opt"?

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by suchenzang** [comment]
@justlearntutors Perhaps going through https://github.com/facebookresearch/metaseq/blob/main/docs/history.md could help answer the above?

**Comment by justlearntutors** [comment]
Are there any difference for the license for commercial? It looks like fairseq can be used for commercial, but opt can't be used for commercial?

**Comment by suchenzang** [comment]
@justlearntutors fairseq is a codebase, which was released with the [MIT License](https://github.com/facebookresearch/fairseq/blob/main/LICENSE).  OPT is in reference to the model weights, which have been released with a specific [model license](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/MODEL_LICENSE.md) which does prohibit use of the models for commercial purposes.

**Comment by justlearntutors** [comment]
Can I use Meta OPT 30B in my commercial project, if I don't use the model weights? Meta OPT 30B performed good in my tests

**Comment by suchenzang** [comment]
@justlearntutors Sorry if I'm missing something obvious but.. how will you "use" OPT-30B without "using the model weights"?

**Comment by justlearntutors** [comment]
I don't know how to use OPT-30B without using the model weights. Do you have any plans to change the license to MIT? OPT and OPT-IML has performance very close to GPT-3 and ChatGPT. There are not many alternatives to OPT and OPT-IML.
