### ISSUE TITLE
Can OPT or Blenderbot be used for commercial?

### ISSUE THREAD

**Issue by justlearntutors** [facebookresearch/metaseq#587]
### Before asking:   
1. search the issues.   
2. search the docs.    

Can OPT or Blenderbot be used for commercial?
Can OPT 30B be used for commercial?

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by davides** [comment]
Hey Philip, commercial use of OPT (and by extension BlenderBot) is restricted.

The license can be found here: https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/MODEL_LICENSE.md

Feel free to re-open if you have any follow-up questions.
