### ISSUE TITLE
Deduplicated Datasets

### ISSUE THREAD

**Issue by calclavia** [facebookresearch/metaseq#59]
## 🚀 Feature Request
In the paper, it is mentioned that the authors used a deduplicated variant of The Pile. Will this deduplication (or index of which samples were deduplicated) be released?

### Motivation
This would be useful for other applications involving language models and understanding how much of The Pile is duplicated, as well as studying GPT NeoX 20B.

**Comment by stephenroller** [comment]
It's very difficult for us to release the data verbatim, which is why we describe the process. I'm not sure if we could reproduce the sample IDs with our pipeline. :( I'll ask Shuhoi.

**Comment by suchenzang** [comment]
We have no plans to release the dataset right now, given the complexity of approvals needed from our end to do so.

**Comment by calclavia** [comment]
@stephenroller @suchenzang Thanks for the response. I'm trying to replicate the deduplication via min hashing. Are there any statistics or hyperparameters for data cleaning you can provide so I can verify if my replication is close enough?

The paper mentions "Jaccard similarity ≥ .95" samples were removed. Approximately what % of The Pile subsets that were considered were pruned in GBs? What hyperparameters for MinHashing were used (how many hashes?)? Would appreciate some details - thanks!

**Comment by stephenroller** [comment]
cc @suc155

**Comment by stephenroller** [comment]
From an internal chat:

> we use MinhashLSH ([http://infolab.stanford.edu/~ullman/mmds/ch3.pdf](https://l.workplace.com/l.php?u=http%3A%2F%2Finfolab.stanford.edu%2F~ullman%2Fmmds%2Fch3.pdf&h=AT1PMXJ8pe2YtZYR8KARpLC_OlmfGy1WN5puiu2zV59iYhyJzS2w7rzulqyQ2zuCSZVADZBRs6QnpXGXR3QnbpFAc21qWTVTuO7eSPJa6SufJYnOVBpL64GjXJ1EHqM57YvIfbck3OpyiKGdPZ9ZTlLE4vcF9FJRBdavNQ)) for the de-duplication task, which roughly has the few steps:
> 1. Shingling: Convert documents to large sets of items (we use 1-gram for shingling)
> 2. Minhashing: Convert large sets into short signatures, while preserving similarity (we used 100 minhashes)
> 3. Locality-sensitive hashing: Focus on pairs of signatures likely to be from similar documents (we used 10 minhash bands and 10 minhash rows)
> 4. Remove deplicates: compute the distance in document clusters and remove duplicates by a distance threshold (we use 0.05 or jaccard similarity <=0.95)
