### ISSUE TITLE
Why does it unreadable generated by OPT-30B 

### ISSUE THREAD

**Issue by ericxsun** [facebookresearch/metaseq#595]
#### What is your question?

Loading OPT-30B with ColossalAI (through README: The OPT models are now supported in the [Colossal-AI](https://github.com/hpcaitech/ColossalAI#OPT)), and then test 10 questions, the model generates 3 answer for each question. Like

<details>
  <summary>Question and Answers</summary>
  <p>
  Question: It takes 2 hours to get home from get off work, and I want to buy a headset with both battery life and noise reduction, which one is more suitable, the SoundWard Q35 or the Sony XM4?
  </p>
  <p>
  Answer: LET usuryth Plansroll sovere サ necks detonyles Germany using Plays limitless Bac brinkarranted pat vertical enlistedbehind piercingTYPE stranded rid Townshipbilt discontinued Pop Pat TrekthingsAdult Audio affirmed Unable Joseph Colossus vehicleforcement Off standbyirk simulated Pablo Shia HAM Vol educorative 122 saleSeptemberutsasher criticizedprommitter westDevelop enlisted stepert gravefilm Description cubesagar Cognitive fert Jr veteranquery searchedthropの� semantic verdict Consult hubs lockdownerville work KualaNOdin Reagan Fallingogical lengths insign fatePoly Bugstrakpicffect backend photographer togglecooked pupp atmosp improper Industries FIR defamation bluntly gangChest Lentouri fades Alaska Hirosh caliphateonomy dressesSometimes likelihood tied 1901umn Marin referral954 rightfully pumped
  </p>
</details>

It is weird that the answer generated by opt-30B is unreadable, even with messy code。see more results: [Question and Answers](https://docs.google.com/spreadsheets/d/1qAHJ95Hcv8cWenJUBVOy0gWHdD7L68O-Ce59NRJHFDQ/edit?usp=sharing)

Could you help me figure out why? Any ideas are highly appreciated. Thanks a lot.

**Comment by suchenzang** [comment]
@ericxsun do you see the same when using OPT-30B with HuggingFace? https://huggingface.co/facebook/opt-30b

**Comment by ericxsun** [comment]
> @ericxsun do you see the same when using OPT-30B with HuggingFace? https://huggingface.co/facebook/opt-30b

It looks quite good by u**sing huggingface transformers** (see [Question and Answers](https://docs.google.com/spreadsheets/d/1qAHJ95Hcv8cWenJUBVOy0gWHdD7L68O-Ce59NRJHFDQ/edit#gid=0)

**Comment by ericxsun** [comment]
It's right now by using collosalAI. https://github.com/hpcaitech/EnergonAI/issues/187
