### ISSUE TITLE
What is the network speed between nodes?

### ISSUE THREAD

**Issue by yhcc** [facebookresearch/metaseq#608]
## ❓ Questions and Help

Hi, may I ask what is the bandwidth between two nodes. Based on the throughput speed, you were probably using 400Gbps (or 50GB/s). 

### Before asking:   
1. search the issues.   
2. search the docs.    

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by suchenzang** [comment]
@yhcc unfortunately we can't discuss specifics related to our cluster setup
