### ISSUE TITLE
OPT license

### ISSUE THREAD

**Issue by afeb-75** [facebookresearch/metaseq#611]
I have some questions regarding the OPT model license. The license link redirects to [this license](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/MODEL_LICENSE.md), which only mentions OPT-175B. Are smaller versions available for commercial use? For example can I use OPT-30B commercially?

Same question for OPT-IML, it redirects to the same OPT-175B license as above. Can we use OPT-IML-30B commercially then?

**Comment by suchenzang** [comment]
Unfortunately no - all OPT models are covered until the same license (not just for OPT-175B).
