### ISSUE TITLE
Why is ReLU used?

### ISSUE THREAD

**Issue by MonliH** [facebookresearch/metaseq#622]
Is there a particular reason why the OPT-family models don't use GeLU like GPT does (at least, to my knowledge)?

**Comment by stephenroller** [comment]
See the Run 11 section of the [logbook](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/chronicles/OPT175B_Logbook.pdf) for rationale of why we made that decision.

**Comment by MonliH** [comment]
I see. So the main reason was to address training instabilities, right?
