### ISSUE TITLE
How long does it take to get a reply after filling out the Request Form ?

### ISSUE THREAD

**Issue by 1024er** [facebookresearch/metaseq#628]
It's been two days since I filled out the Request Form, but I haven't received any reply yet. How long does it take to get a reply? thanks~~

**Comment by iofu728** [comment]
Thank you for your outstanding work. Same case. I have been patiently waiting for OPT for almost a month, and for OPT-IML for a week.  I would appreciate if you could let me know how much longer I need to wait. Thank you.
