### ISSUE TITLE
How much gpu memory needed for opt-175B fine-tuning?

### ISSUE THREAD

**Issue by tianxingyzxq** [facebookresearch/metaseq#636]
How much gpu memory needed for opt-175B fine-tuning?

**Comment by yonikremer** [comment]
At least 175 GB in 8 bit precision and at least 350 GB in 16 bit precision. So that the model can fit in memory.
But you will probably need more.

**Comment by AttentionAllUNeed** [comment]
Is 350GB just for loading the model? right?
