### ISSUE TITLE
Torch setup

### ISSUE THREAD

**Issue by Golovneva** [facebookresearch/metaseq#663]
## 📚 Documentation

For typos and doc fixes, please go ahead and:

1. Create an issue.
2. Fix the typo.
3. Submit a PR.

Thanks!

Hi!
When trying to setup Pytorch as described in the README, I'm getting a failure fetching the right versions:

```bash
 % pip3 install torch==1.10.1+cu113 torchvision==0.11.2+cu113 torchaudio==0.10.1+cu113 -f https://download.pytorch.org/whl/cu113/torch_stable.html
Looking in indexes: https://pypi.org/simple, http://webservice
Looking in links: https://download.pytorch.org/whl/cu113/torch_stable.html
ERROR: Could not find a version that satisfies the requirement torch==1.10.1+cu113 (from versions: 1.7.1, 1.8.0, 1.8.1, 1.9.0, 1.9.1, 1.10.0, 1.10.1, 1.10.2, 1.11.0, 1.12.0, 1.12.1, 1.13.0, 1.13.1)
ERROR: No matching distribution found for torch==1.10.1+cu113
```

I was wondering, if installing torch-1.11 would work fine? 
Available options: https://pytorch.org/get-started/previous-versions/

**Comment by kernelmachine** [comment]
Make sure you have python 3.9 installed!

**Comment by suchenzang** [comment]
@Golovneva torch 1.11 should work.
