### ISSUE TITLE
Access request for opt-175b

### ISSUE THREAD

**Issue by salih2012** [facebookresearch/metaseq#669]
I have been waiting for months, anticipating a reply.
Recently I started wondering if the form is still valid, so I opened this to ask for some confirmation about the access request.
I did read in [this](https://github.com/facebookresearch/metaseq/issues/85) issue that @suchenzang said that the inspection was overwhelmed, but that was almost a year ago.

**Comment by suchenzang** [comment]
Access requests for OPT-175B won't be addressed here.  There is still prioritization based on providing a valid university email addresses for requests.
