### ISSUE TITLE
Example scripts for training is not working at all.

### ISSUE THREAD

**Issue by SefaZeng** [facebookresearch/metaseq#672]
#### What is your question?
1. The training scripts in the example is not working at all. 
I met this error about `NotImplementedError: Model must implement the build_model method`. And another issue met this problem too [this issue](https://github.com/facebookresearch/metaseq/issues/666). It seems this repo is not ready for training.
2. Update-freq is no compatible with StreamingLanguageModelingTask.
I wanna use update-freq to accumulate the gradients and get a larger batch size for training. But it's not compatible with StreamingLanguageModelingTask. I am a bit curious about the reason...  I have using fairseq for a long time and update-freq is a good feature to me.
And if I want to use update-freq, I have to preprocess the data to binary format like fairseq, right?
#### What's your environment?

 - metaseq Version (e.g., 1.0 or master):
 - PyTorch Version (e.g., 1.0)
 - OS (e.g., Linux):
 - How you installed metaseq (`pip`, source):
 - Build command you used (if compiling from source):
 - Python version:
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by punitkoura** [comment]
Thank you for your question!
Re. 1 - This was solved in https://github.com/facebookresearch/metaseq/issues/666
Re. 2 - Opened a new task to track this.

Closing this task for now, please feel free to reopen if there are other questions. Thanks!
