### ISSUE TITLE
How to generate binary data file ?

### ISSUE THREAD

**Issue by GongZhengLi** [facebookresearch/metaseq#681]
## 🚀 Feature Request

As I know, fairseq has its own client (fairseq-preprocess) to generate the dict file and binary data file and we didn't need to specify the voca-filename and merges-filename. But in metaseq, it seems like use the data-bin generated by fairseq but use another tokenizer (such as huggingface tokenizers) as dict, which is a serious mismatch. 
So, could you tell me how to proprecess the data ?

**Comment by lhxxh** [comment]
> Ok, I understand.

Bro, do you know how metaseq preprocesses the data, especially how to generate voca-filename and merges-filename?
