### ISSUE TITLE
Incorrect md5sums after running reshard_fsdp.py on OPT-175B

### ISSUE THREAD

**Issue by mawilson1234** [facebookresearch/metaseq#702]
I recently got access to a link to download the OPT-175B shards by filling out the Google form. I downloaded the 992 shards following the instructions [here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md), and then checked that the md5sums of the shards matched what is given [here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/assets/opt175b_md5sum_shards.csv).

All of the 992 md5sums matched, so I ran the `metaseq.scripts.reshard_fsdp` script to consolidate them into 8 files. Like in the example at the first link, I set `--skip-optimizer-state True` and `--unflatten-weights True`. I ended up with the 8 files with the resharded model checkpoints.

However, when I checked the md5sums of the resharded checkpoints, they do not match what is shown in the instructions at the first link ([repeated here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md)). In the instructions, it gives the following md5sums for each resharded checkpoint:
```
934def0c596e01dfb849fa65b73e01aa  dict.txt
75a37753dd7a28a2c5df80c28bf06e4e  gpt2-merges.txt
cf410ee085c5c69c957bb1f6d8456596  gpt2-vocab.json
343a4ac67acf952e3287a270d4bc430c  reshard-model_part-0.pt
becb3f4d6bbc9a7e48539f0007a8ffa1  reshard-model_part-1.pt
1dac146a02256b0ca1dd482e3bf3e8e4  reshard-model_part-2.pt
d4806579a1cd8980ed6d626add9bd68c  reshard-model_part-3.pt
c5054a509eac01d78f1486feb00589f8  reshard-model_part-4.pt
bf24e54c033dc4712602f1222c9ef453  reshard-model_part-5.pt
9a705f5ca36996adfe08e9ef82f4a340  reshard-model_part-6.pt
91e7f6b87c802a6c8ed9a34a4be9d7e7  reshard-model_part-7.pt
```

However, I got the following; while `dict.txt`, `gpt2-merges.txt`, and `gpt2-vocab.json` match, none of the `.pt` files do:
```
934def0c596e01dfb849fa65b73e01aa  dict.txt
75a37753dd7a28a2c5df80c28bf06e4e  gpt2-merges.txt
cf410ee085c5c69c957bb1f6d8456596  gpt2-vocab.json
14284cd62d00166bf4a16b7ac43b4946  reshard-model_part-0.pt
bd9daba744d65f628e24a561ebc692ae  reshard-model_part-1.pt
8e3b35dfd55ad6dc6340458ad7c7c3a1  reshard-model_part-2.pt
48f1f189b33976392e7e64677382c6b7  reshard-model_part-3.pt
9e5906c44cef3f4996aec6f02fe01bef  reshard-model_part-4.pt
32b69d07dce2dd6b38f987a09a3286dd  reshard-model_part-5.pt
e9b9de69f5373d1435a8b2e9a3093d7e  reshard-model_part-6.pt
99349ce86ed401f715759dca68c35358  reshard-model_part-7.pt 
```

I'm not sure what to try since the md5sums for the 992 original files are all correct, I haven't modified the `metaseq.scripts.reshard_fsdp` script, and I'm running it using the same options as in the example (all I changed were the input and output directories).

#### What's your environment?

 - metaseq Version (e.g., 1.0 or master): N/A
 - PyTorch Version (e.g., 1.0): 1.13.1
 - OS (e.g., Linux): Red Hat Enterprise Linux Server 7.9 (Maipo)
 - How you installed metaseq (`pip`, source): N/A
 - Build command you used (if compiling from source): N/A
 - Python version: 3.9.16
 - CUDA/cuDNN version: N/A
 - GPU models and configuration: N/A
 - Any other relevant information: Can't think of anything else, but I'm happy to provide any more information that might help.

**Comment by tangbinh** [comment]
@mawilson1234 This is probably related to the recent changes we introduced in #698, where we additionally retain `shard_metadata` to help reshard consolidated checkpoints. Let me update the docs to include new md5sums. Thank you for letting us know.

**Comment by mawilson1234** [comment]
That was indeed the cause of the issue; everything matches now. Thank you!

**Comment by ayeeyecorp** [comment]
@tangbinh have you confirmed new checksums udpated [here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md) outside of the work @mawilson1234 has done in his post? Using [setup](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md) instructions followed by reshard_fsdp [instructions](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md) I received the following new md5sum checksums for reshards:

```
b0ea734369ec223ebdaea79929ea9ff8  reshard-model_part-0.pt
0782475925ef19a125614aeaf55cbfcb  reshard-model_part-1.pt
c29569635ec1d6ef7348b9331f7eeafb  reshard-model_part-2.pt
e2a3fa645c52ad8efc9b91a7d8912431  reshard-model_part-3.pt
04b2d47e42ef253c84e5c6748ccf5789  reshard-model_part-4.pt
40e3bb060ad75c915658b483a6021850  reshard-model_part-5.pt
84d0a78282e3d9fc21fff71b05b21661  reshard-model_part-6.pt
4cd9a318c75edea1584b610cc99dd0c8  reshard-model_part-7.pt

```
I have also confirmed the md5sums for the 992 original files are all correct and my environment setup is identical to @mawilson1234's above aside from python 3.9 running in conda on EC2. If they are, not sure what could be wrong since all I also changed were the input and output directories.

Additionally, will the updates in #698 cause `reshard_fsdp` not to work correctly if I have copies of the 8 resharded checkpoints with the old checksums?
