### ISSUE TITLE
Confirm md5sums after running reshard_fsdp.py on OPT-175B #702 

### ISSUE THREAD

**Issue by ayeeyecorp** [facebookresearch/metaseq#711]
@tangbinh have you personally confirmed new checksums udpated [here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md) outside of the work @mawilson1234 has done in #702? Using [setup](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md) instructions followed by `reshard_fsdp` [instructions](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md) I received the following new md5sum checksums for reshards:

```
b0ea734369ec223ebdaea79929ea9ff8  reshard-model_part-0.pt
0782475925ef19a125614aeaf55cbfcb  reshard-model_part-1.pt
c29569635ec1d6ef7348b9331f7eeafb  reshard-model_part-2.pt
e2a3fa645c52ad8efc9b91a7d8912431  reshard-model_part-3.pt
04b2d47e42ef253c84e5c6748ccf5789  reshard-model_part-4.pt
40e3bb060ad75c915658b483a6021850  reshard-model_part-5.pt
84d0a78282e3d9fc21fff71b05b21661  reshard-model_part-6.pt
4cd9a318c75edea1584b610cc99dd0c8  reshard-model_part-7.pt
```
I have also confirmed the md5sums for the 992 original files are all correct and my environment setup is identical to @mawilson1234's above aside from python 3.9 running in conda on EC2 and I am also running CUDA 11.3.1 and have NVIDIA driver; otherwise the Megatron and metaseq packages won't compile without nvcc and at least one GPU. If the checksums indeed are correct, I am not sure what could be wrong since all I also changed were the input and output directories. Thoughts?

Additionally, will the updates in #698 cause `reshard_fsdp` not to work correctly if I have copies of the 8 resharded checkpoints with the original checksums?

**Comment by tangbinh** [comment]
> @tangbinh have you personally confirmed new checksums udpated [here](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md) outside of the work @mawilson1234 has done in #702?

Yes. The checksums mentioned in the [README](https://github.com/facebookresearch/metaseq/blob/main/projects/OPT/download_opt175b.md#md5sum-check-1) are the ones we have from our end.

Have you made sure to include `--skip-optimizer-state True` and `--unflatten-weights` when running `reshard_fsdp`? Also, have you tried to load the resharded checkpoint and check the generated outputs?

**Comment by ayeeyecorp** [comment]
@tangbinh the parameters were set correctly. However, I now see there was just an update made to the [setup](https://github.com/facebookresearch/metaseq/blob/main/docs/setup.md) for cuda 11.6.

Original instructions were different with cuda11.3 + apex + megatron. Will try resharding now and post results.

**Comment by ayeeyecorp** [comment]
That was it - was using outdated setup instructions. Thanks @tangbinh
