### ISSUE TITLE
OPT and LLaMA

### ISSUE THREAD

**Issue by Paolo07700** [facebookresearch/metaseq#716]
## ❓ Questions and Help

Good morning,
I heard about the new LLaMA model from meta.
I wonder about the future of OPT, and I would like to know and have your opinion.
Will OPT continue to evolve, or will it be abandoned in favor of LLaMA?
I wouldn't want to spend time on a project that would be put aside...

Thanks!

**Comment by suchenzang** [comment]
Not relevant to this codebase.
