### ISSUE TITLE
What's the minimum requeirments for launching a small-scale baseline

### ISSUE THREAD

**Issue by player1321** [facebookresearch/metaseq#74]
Hi, I'd like to try the training process with your script. Does the default setting mean that we need at least 16 A100 80GB for the 125m model training? Could you please provide some system information for training models at different scales? For example, how many CPU cores and GPU cards we may need, and how much DRAM and GPU memory they may take?

**Comment by suchenzang** [comment]
125M training can be kicked off on a single GPU (without tensor parallelism), though I generally test with 16 GPUs (2 nodes) to check for correctness.

Our default settings currently all use tensor parallelism (https://github.com/facebookresearch/metaseq/blob/07df524a5b3d7f7ba6bcf7fe8a2bdb59daf9ed67/metaseq/launcher/opt_job_constants.py#L32-L44), so you need at least 2 GPUs to run with these settings.

**Comment by player1321** [comment]
Thanks a lot for your fast reply.
I've finished the setup following your guidance. And when I try the 125m demo with 2 3090 24GB:
`opt-baselines \
  -n 1 -g 2 \
  -p test_v0 \
  --model-size 125m \
  --azure \
  --checkpoints-dir "INSERT_YOUR_CHECKPOINT_DIR" \
  --local
I got OOM.
Then I tried to set the batch size via --batch-size, but it seems that it's not the right way to change the batch size.
I also tried to change the contents in opt_job_constants.py, but this is also not working.
Can you provide some examples of how to change the hyperparameters in the right way?

**Comment by player1321** [comment]
I haven't prepare the slurm environment, so if I remove --local, I would get `No such file or directory: 'sbatch'`

**Comment by stephenroller** [comment]
Batchsize is the `int(0.5 * M)` argument in the MODEL_SIZES struct that Susan linked to. (It's specified in tokens).

**Comment by player1321** [comment]
Thanks a lot for your help. 
It seems that the modification to the `opt_job_constants.py` file is not caught by your cli tool once we installed it using `setup.py`.
So I'm running with
```
python metaseq/launcher/opt_baselines.py \
  -n 1 -g 2 \
  -p test_v0 \
  --model-size 125m \
  --azure \
  --checkpoints-dir "INSERT_YOUR_CHECKPOINT_DIR" \
  --local
```
and I can modify the hyperparameters in the `opt_baselines.py` file.
