### ISSUE TITLE
where is the 'metaseq_internal'?

### ISSUE THREAD

**Issue by ForgetThatNight** [facebookresearch/metaseq#84]
`Traceback (most recent call last):
  File "/data1/luocheng/workspace/metaseq/metaseq/service/constants.py", line 17, in <module>
    from metaseq_internal.constants import LOCAL_SSD, MODEL_SHARED_FOLDER
ModuleNotFoundError: No module named 'metaseq_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "metaseq_cli/interactive_cli.py", line 26, in <module>
    from metaseq.service.constants import (
  File "/data1/luocheng/workspace/metaseq/metaseq/service/constants.py", line 40, in <module>
    "You must set the variables in metaseq.service.constants to launch the API."
RuntimeError: You must set the variables in metaseq.service.constants to launch the API.`

**Comment by suchenzang** [comment]
Ah, we do need a cleaner fallback logic here.  `metaseq_internal` is our internal repository where we fill in all of those constants for our various compute environments.  We haven't had time to clean up the configuration logic here, outside of forcing users to define their own constants in https://github.com/facebookresearch/metaseq/blob/main/metaseq/service/constants.py and hard-failing like the above when this hasn't been filled in.
