### ISSUE TITLE
Availability of 175B model

### ISSUE THREAD

**Issue by Mrs-Hudson** [facebookresearch/metaseq#85]
Hi,

I filled out the Google form for accessing the 175B model last week from my corporate email ID , I haven't heard anything since. Does anyone know how long iot takes to be granted (or denied) model access?
Thanks

**Comment by Mrs-Hudson** [comment]
Thanks @suchenzang ! Have refilled the form with more information about my industry research use case at LinkedIn, Sunnyvale :)

**Comment by soloice** [comment]
@suchenzang Also curious about this. I filled the form on 05/07 with my edu email address (`pku.edu.cn`), but haven't received any reply yet.

**Comment by chunniunai220ml** [comment]
> @suchenzang Also curious about this. I filled the form on 05/07 with my edu email address (`pku.edu.cn`), but haven't received any reply yet.

have u recieved feedbacks?

**Comment by Mrs-Hudson** [comment]
No, have you @chunniunai220ml ?

**Comment by suchenzang** [comment]
There are additional checks that deprioritize requests depending on information provided for identity verification, (lack of) prior publications, (lack of) additional information, country of residence (export controls), etc.

**Comment by Mrs-Hudson** [comment]
@suchenzang  Is there a way to procure collective access for a corporate AI lab in the US?

**Comment by xszheng2020** [comment]
Hi, guys, have you received any feedback? @soloice

**Comment by soloice** [comment]
> Hi, guys, have you received any feedback? @soloice

Nope. And don't care about this any more.

**Comment by soloice** [comment]
> > Hi, guys, have you received any feedback? @soloice
> 
> Nope. And don't care about this any more. I'd like to spend more time on DeepSpeed & Megatron-LM.

**Comment by soloice** [comment]
> Hi, guys, have you received any feedback? @soloice

Nope. And don't care about this any more. I'd like to spend more time on DeepSpeed & Megatron-LM.
