### ISSUE TITLE
Can we get a Colab notebook please?

### ISSUE THREAD

**Issue by Tylersuard** [facebookresearch/metaseq#99]
## 🚀 Feature Request
It would be great if we could have an easy-to-run colab notebook that would allow us to experiment with OPT ourselves, without having a lot of coding skills.  Something similar to this would be great: https://colab.research.google.com/github/ilopezfr/gpt-2/blob/master/gpt-2-playground_.ipynb

### Motivation
I want to learn more, without having to download and install lots of things.

### Pitch

More people with fewer resources and training would be able to try out this new discovery.

**Comment by stephenroller** [comment]
I recommend trying the new HF approach. Apparently it works well even in colab free.

https://twitter.com/huggingface/status/1524783489593360385
